// Spot the Error: a sentence in 4 parts. bad = index of the part with the mistake (0-3), or 4 if there is no error.
export const ERRORS = [
  // ===== Level 1 (grades 4-5) =====
  { id: 'e001', lv: 1, parts: ['My little brother', 'have a pet turtle', 'that likes to eat', 'strawberries.'], bad: 1, fix: 'has a pet turtle', why: 'Brother is one person, so the verb is has, not have.' },
  { id: 'e002', lv: 1, parts: ['Me and Jake', 'built a huge fort', 'out of couch cushions', 'last Saturday.'], bad: 0, fix: 'Jake and I', why: 'Use I for the subject. Test it: you would say "I built," not "Me built."' },
  { id: 'e003', lv: 1, parts: ['The dog wagged', 'it\'s tail so hard', 'that it knocked over', 'a glass of juice.'], bad: 1, fix: 'its tail so hard', why: 'Its (no apostrophe) shows ownership. It\'s always means "it is" or "it has."' },
  { id: 'e004', lv: 1, parts: ['After the game,', 'the players took off', 'there muddy cleats', 'and headed for the bus.'], bad: 2, fix: 'their muddy cleats', why: 'Their shows that something belongs to them. There is a place.' },
  { id: 'e005', lv: 1, parts: ['We should of', 'brought more snacks', 'for the long', 'car ride.'], bad: 0, fix: 'We should have', why: 'It is should have. "Should of" only sounds right because should\'ve sounds like it.' },
  { id: 'e006', lv: 1, parts: ['Our goalie played', 'really good', 'in the second half', 'of the championship game.'], bad: 1, fix: 'really well', why: 'Well is the adverb that tells how someone played. Good describes nouns.' },
  { id: 'e007', lv: 1, parts: ['My new skateboard is', 'more faster', 'than the one', 'I got last year.'], bad: 1, fix: 'faster', why: 'Faster already means "more fast." Never use more with an -er word.' },
  { id: 'e008', lv: 1, parts: ['I don\'t have', 'no homework tonight,', 'so I can play', 'video games after dinner.'], bad: 1, fix: 'any homework tonight,', why: 'Don\'t and no together make a double negative. Use any after don\'t.' },
  { id: 'e009', lv: 1, parts: ['Yesterday my cousin', 'throwed the football', 'all the way across', 'the backyard.'], bad: 1, fix: 'threw the football', why: 'Throw is irregular. The past tense is threw, not throwed.' },
  { id: 'e010', lv: 1, parts: ['The boys\' locker room', 'smelled like', 'old socks', 'and wet towels.'], bad: 4, fix: '', why: 'No error. The room belongs to many boys, and boys already ends in s, so the apostrophe goes after the s: boys\'.' },
  { id: 'e011', lv: 1, parts: ['A shark can smell', 'blood from far away,', 'it is one of', 'the ocean\'s best hunters.'], bad: 1, fix: 'blood from far away;', why: 'Two complete sentences cannot be glued together with just a comma. Use a semicolon or a period.' },
  { id: 'e012', lv: 1, parts: ['Their are', 'three dinosaur skeletons', 'in the museum\'s', 'main hall.'], bad: 0, fix: 'There are', why: 'There are tells that something exists. Their means "belonging to them."' },
  { id: 'e013', lv: 1, parts: ['Homemade pizza tastes', 'much better then', 'the frozen kind', 'from the store.'], bad: 1, fix: 'much better than', why: 'Use than to compare. Then is about time (first this, then that).' },
  { id: 'e014', lv: 1, parts: ['You\'re going to love', 'the new roller coaster,', 'but hold on to', 'you\'re hat!'], bad: 3, fix: 'your hat!', why: 'Your shows ownership. You\'re means "you are," and "hold on to you are hat" makes no sense.' },
  { id: 'e015', lv: 1, parts: ['Mom gave', 'my brother and I', 'tickets to the', 'monster truck show.'], bad: 1, fix: 'my brother and me', why: 'Me is the object of gave. Test it: Mom gave me tickets, not Mom gave I tickets.' },
  { id: 'e016', lv: 1, parts: ['Each of the players', 'gets a new jersey', 'before the first', 'game of the season.'], bad: 4, fix: '', why: 'No error. The subject is each, which is singular, so gets is correct even though players is plural.' },
  { id: 'e017', lv: 1, parts: ['The batteries in my', 'remote-control car', 'is dead', 'again.'], bad: 2, fix: 'are dead', why: 'The subject is batteries (plural), not car, so the verb is are.' },
  { id: 'e018', lv: 1, parts: ['Last summer we', 'swimmed in the lake', 'every single day', 'at camp.'], bad: 1, fix: 'swam in the lake', why: 'Swim is irregular: swim, swam, swum. There is no word swimmed.' },
  { id: 'e019', lv: 1, parts: ['There are', 'fewer cookies in the jar', 'than there were', 'this morning.'], bad: 4, fix: '', why: 'No error. Use fewer for things you can count, like cookies. Less is for things you cannot count, like milk.' },
  { id: 'e020', lv: 1, parts: ['Who\'s backpack', 'is sitting', 'in the middle of', 'the hallway?'], bad: 0, fix: 'Whose backpack', why: 'Whose asks who owns something. Who\'s means "who is."' },
  { id: 'e021', lv: 1, parts: ['Our teacher', 'told us to', 'bring are library books', 'back by Friday.'], bad: 2, fix: 'bring our library books', why: 'Our shows ownership. Are is a verb, as in "we are."' },
  { id: 'e022', lv: 1, parts: ['That was', 'the most funniest', 'joke I have', 'ever heard!'], bad: 1, fix: 'the funniest', why: 'Funniest already means "most funny." Never use most with an -est word.' },
  { id: 'e023', lv: 1, parts: ['The ninja moved', 'so quiet', 'that nobody in the castle', 'heard him.'], bad: 1, fix: 'so quietly', why: 'The word tells how the ninja moved, so it must be the adverb quietly.' },
  { id: 'e024', lv: 1, parts: ['Him and his dad', 'went fishing', 'and caught', 'three huge trout.'], bad: 0, fix: 'He and his dad', why: 'Use he for the subject. Test it: "He went fishing," not "Him went fishing."' },
  { id: 'e025', lv: 1, parts: ['Lightning flashed', 'across the sky,', 'thunder', 'shook the windows.'], bad: 1, fix: 'across the sky, and', why: 'Two complete sentences joined by only a comma make a comma splice. Add and after the comma.' },
  { id: 'e026', lv: 1, parts: ['The robot', 'lifted the box', 'and then it', 'drops it on the floor.'], bad: 3, fix: 'dropped it on the floor.', why: 'The sentence starts in the past (lifted), so it must stay in the past: dropped.' },
  { id: 'e027', lv: 1, parts: ['I have', 'ate three slices', 'of pepperoni pizza', 'already.'], bad: 1, fix: 'eaten three slices', why: 'After have, use the past participle: have eaten, not have ate.' },
  { id: 'e028', lv: 1, parts: ['My grandma', 'has four cat\'s,', 'and all of them', 'sleep on her bed.'], bad: 1, fix: 'has four cats,', why: 'A plural just adds s. An apostrophe is only for ownership, and nothing belongs to the cats here.' },
  { id: 'e029', lv: 1, parts: ['Nobody on our team', 'has ever', 'scored a goal', 'from that far away.'], bad: 4, fix: '', why: 'No error. Nobody is singular, so has is correct.' },
  { id: 'e030', lv: 1, parts: ['The test was', 'to hard', 'for most of', 'the class.'], bad: 1, fix: 'too hard', why: 'Too means "more than enough." To shows direction, as in "go to school."' },
  { id: 'e031', lv: 1, parts: ['The children\'s', 'soccer game', 'was canceled', 'because of rain.'], bad: 4, fix: '', why: 'No error. Children is already plural without an s, so you add \'s: children\'s.' },
  { id: 'e032', lv: 1, parts: ['I seen', 'a bald eagle', 'at the park', 'yesterday.'], bad: 0, fix: 'I saw', why: 'The past tense of see is saw. Seen needs a helper, as in "I have seen."' },
  { id: 'e033', lv: 1, parts: ['My brother', 'doesn\'t like', 'nothing', 'except chicken nuggets.'], bad: 2, fix: 'anything', why: 'Doesn\'t and nothing together make a double negative. Use anything.' },
  { id: 'e034', lv: 1, parts: ['Your', 'going to need', 'a flashlight', 'in the cave.'], bad: 0, fix: 'You\'re', why: 'You\'re means "you are": you are going to need. Your shows ownership.' },
  { id: 'e035', lv: 1, parts: ['Our dog is', 'the bigger', 'of the two dogs', 'on our street.'], bad: 4, fix: '', why: 'No error. When you compare only two things, use the -er form (bigger), not the -est form.' },

  // ===== Level 2 (grades 5-6) =====
  { id: 'e036', lv: 2, parts: ['The box of', 'old comic books', 'were sitting', 'in the attic.'], bad: 2, fix: 'was sitting', why: 'The subject is box (one box), not books. So the verb is was.' },
  { id: 'e037', lv: 2, parts: ['Everyone in the stands', 'were cheering', 'when the ball', 'went in.'], bad: 1, fix: 'was cheering', why: 'Everyone is singular, even though it means a lot of people. Use was.' },
  { id: 'e038', lv: 2, parts: ['The coach', 'gave Marcus and I', 'a high five', 'after the game.'], bad: 1, fix: 'gave Marcus and me', why: 'Me is the object of gave. Drop Marcus and test it: "gave me a high five."' },
  { id: 'e039', lv: 2, parts: ['I could of', 'won the race', 'if my shoe', 'hadn\'t come untied.'], bad: 0, fix: 'I could have', why: 'It is could have (could\'ve). "Could of" is never correct.' },
  { id: 'e040', lv: 2, parts: ['My uncle and I', 'went to', 'the hockey game', 'on Friday night.'], bad: 4, fix: '', why: 'No error. My uncle and I is the subject of went, so I is correct. Test it: "I went to the game."' },
  { id: 'e041', lv: 2, parts: ['The dragon spread', 'it\'s enormous wings', 'and flew', 'over the village.'], bad: 1, fix: 'its enormous wings', why: 'The wings belong to the dragon, so use its. It\'s means "it is."' },
  { id: 'e042', lv: 2, parts: ['When the bell rang,', 'everyone runs', 'out to', 'the playground.'], bad: 1, fix: 'everyone ran', why: 'Rang is past tense, so the rest of the sentence must be past too: ran.' },
  { id: 'e043', lv: 2, parts: ['The bike was', 'laying', 'in the driveway', 'all night.'], bad: 1, fix: 'lying', why: 'Lie means to rest. Lay means to put something down. The bike was resting, so it was lying.' },
  { id: 'e044', lv: 2, parts: ['There is', 'two pizzas', 'left over', 'from the party.'], bad: 0, fix: 'There are', why: 'The subject comes after the verb here: two pizzas. Plural subject, so There are.' },
  { id: 'e045', lv: 2, parts: ['He felt', 'bad', 'about missing', 'the penalty kick.'], bad: 4, fix: '', why: 'No error. Feel is a linking verb, so it takes the adjective bad.' },
  { id: 'e046', lv: 2, parts: ['The astronaut', 'floated', 'more slower', 'than the others in the space station.'], bad: 2, fix: 'more slowly', why: 'Never put more in front of an -er word. The adverb form is more slowly.' },
  { id: 'e047', lv: 2, parts: ['The puppy', 'and the kitten', 'is', 'best friends.'], bad: 2, fix: 'are', why: 'Two subjects joined by and make a plural subject, so the verb is are.' },
  { id: 'e048', lv: 2, parts: ['Whose turn', 'is it', 'to feed', 'the goldfish?'], bad: 4, fix: '', why: 'No error. Whose asks who something belongs to (the turn). Who\'s would mean "who is."' },
  { id: 'e049', lv: 2, parts: ['The players', 'must bring', 'there own water bottles', 'to practice.'], bad: 2, fix: 'their own water bottles', why: 'The bottles belong to the players, so use their.' },
  { id: 'e050', lv: 2, parts: ['My cousin', 'is a better', 'skater', 'then I am.'], bad: 3, fix: 'than I am.', why: 'Use than for comparisons. Then is about time.' },
  { id: 'e051', lv: 2, parts: ['The pond', 'had froze', 'solid by', 'the middle of January.'], bad: 1, fix: 'had frozen', why: 'After had, use the past participle: freeze, froze, frozen.' },
  { id: 'e052', lv: 2, parts: ['We was', 'planning to', 'go camping,', 'but it rained.'], bad: 0, fix: 'We were', why: 'We is plural, so the past form of be is were.' },
  { id: 'e053', lv: 2, parts: ['The wolves howled', 'all night long,', 'nobody at camp', 'got any sleep.'], bad: 1, fix: 'all night long, so', why: 'Two complete sentences need more than a comma between them. Adding so fixes the comma splice.' },
  { id: 'e054', lv: 2, parts: ['I want', 'to go', 'to the arcade', 'to!'], bad: 3, fix: 'too!', why: 'Too means "also." To is for direction, as in "to the arcade."' },
  { id: 'e055', lv: 2, parts: ['The leaves on that tree', 'turns', 'bright red', 'every October.'], bad: 1, fix: 'turn', why: 'The subject is leaves (plural), not tree. Plural subject, so turn.' },
  { id: 'e056', lv: 2, parts: ['I did', 'good', 'on my math test', 'this week.'], bad: 1, fix: 'well', why: 'Well tells how you did something. Good describes a noun, as in "a good test."' },
  { id: 'e057', lv: 2, parts: ['The kids', 'which', 'won the contest', 'got free ice cream.'], bad: 1, fix: 'who', why: 'Use who for people and which for things.' },
  { id: 'e058', lv: 2, parts: ['My dad', 'has drove', 'that old truck', 'for fifteen years.'], bad: 1, fix: 'has driven', why: 'After has, use the past participle: drive, drove, driven.' },
  { id: 'e059', lv: 2, parts: ['The quarterback', 'threw the ball', 'farther', 'than anyone else on the team.'], bad: 4, fix: '', why: 'No error. Farther is used for real distance you can measure, like how far a ball goes.' },
  { id: 'e060', lv: 2, parts: ['The mens\'', 'restroom', 'is', 'down the hall.'], bad: 0, fix: 'The men\'s', why: 'Men is already plural without an s, so add \'s: men\'s.' },
  { id: 'e061', lv: 2, parts: ['The cookies', 'smelled', 'so good', 'that we ate them all.'], bad: 4, fix: '', why: 'No error. Smelled is a linking verb here (the cookies were good), so it takes the adjective good, not well.' },
  { id: 'e062', lv: 2, parts: ['I haven\'t', 'never', 'been', 'to a real rodeo.'], bad: 1, fix: 'ever', why: 'Haven\'t and never together make a double negative. Use ever.' },
  { id: 'e063', lv: 2, parts: ['Of all the planets,', 'Jupiter is', 'the most biggest', 'one.'], bad: 2, fix: 'the biggest', why: 'Biggest already means "most big." Do not use both.' },
  { id: 'e064', lv: 2, parts: ['Tom', 'brung', 'his snake', 'to show-and-tell.'], bad: 1, fix: 'brought', why: 'The past tense of bring is brought. Brung is not standard English.' },
  { id: 'e065', lv: 2, parts: ['Every one of', 'the cupcakes', 'have', 'sprinkles on top.'], bad: 2, fix: 'has', why: 'The subject is one (every one), not cupcakes. One is singular, so has.' },
  { id: 'e066', lv: 2, parts: ['The goalie', 'dove to', 'his left', 'and stopped the shot.'], bad: 4, fix: '', why: 'No error. In American English, dove is a correct past tense of dive.' },
  { id: 'e067', lv: 2, parts: ['We watched', 'the fireworks', 'and then we', 'go home.'], bad: 3, fix: 'went home.', why: 'Watched is past tense, so the second action must be past too: went.' },
  { id: 'e068', lv: 2, parts: ['Please', 'lay', 'your backpacks', 'on the bench.'], bad: 4, fix: '', why: 'No error. Lay means to put something down, and here you put the backpacks down.' },
  { id: 'e069', lv: 2, parts: ['The museum', 'has', 'less dinosaur bones', 'than I expected.'], bad: 2, fix: 'fewer dinosaur bones', why: 'Bones can be counted, so use fewer. Less is for things you cannot count.' },
  { id: 'e070', lv: 2, parts: ['The giant catfish', 'swam', 'real fast', 'toward the boat.'], bad: 2, fix: 'really fast', why: 'Real is an adjective. To make fast stronger, you need the adverb really.' },

  // ===== Level 3 (grade 6) =====
  { id: 'e071', lv: 3, parts: ['Neither of my brothers', 'have finished', 'their science projects,', 'and the fair is tomorrow.'], bad: 1, fix: 'has finished', why: 'Neither is singular, so the verb is has.' },
  { id: 'e072', lv: 3, parts: ['Between you and me,', 'the new video game', 'is not as fun', 'as the first one.'], bad: 4, fix: '', why: 'No error. Between is a preposition, so it takes me. "Between you and I" is the mistake.' },
  { id: 'e073', lv: 3, parts: ['Whom', 'did you', 'invite to', 'your birthday party?'], bad: 4, fix: '', why: 'No error. Whom is the object of invite. Test it: you invited him, and him matches whom.' },
  { id: 'e074', lv: 3, parts: ['The player', 'who the coach chose', 'as captain', 'is my best friend.'], bad: 1, fix: 'whom the coach chose', why: 'The coach chose him, so the pronoun is an object. Use whom.' },
  { id: 'e075', lv: 3, parts: ['One of the', 'astronauts', 'are', 'from my hometown.'], bad: 2, fix: 'is', why: 'The subject is one, not astronauts. One is singular, so the verb is is.' },
  { id: 'e076', lv: 3, parts: ['If I', 'would have known', 'about the test,', 'I would have studied.'], bad: 1, fix: 'had known', why: 'In the if part of a sentence about the past, use had, not would have.' },
  { id: 'e077', lv: 3, parts: ['The video game', 'that my friends and I', 'play every weekend', 'are called Space Raiders.'], bad: 3, fix: 'is called Space Raiders.', why: 'The subject is game (singular). The words in between do not change that, so is called.' },
  { id: 'e078', lv: 3, parts: ['The cold weather', 'did not effect', 'the game,', 'and we won easily.'], bad: 1, fix: 'did not affect', why: 'Affect is usually the verb (to change something). Effect is usually the noun (the result).' },
  { id: 'e079', lv: 3, parts: ['I', 'laid', 'on the couch', 'all afternoon.'], bad: 1, fix: 'lay', why: 'The past tense of lie (to rest) is lay. Laid is the past of lay (to put something down).' },
  { id: 'e080', lv: 3, parts: ['The team accepted', 'the trophy,', 'then they ran', 'a victory lap.'], bad: 1, fix: 'the trophy, and', why: 'Then is not a joining word, so a comma before it creates a comma splice. Add and.' },
  { id: 'e081', lv: 3, parts: ['The number of', 'kids in the chess club', 'has doubled', 'this year.'], bad: 4, fix: '', why: 'No error. The number is singular, so has is correct. ("A number of kids" would take have.)' },
  { id: 'e082', lv: 3, parts: ['Hardly nobody', 'showed up', 'for the', 'early morning practice.'], bad: 0, fix: 'Hardly anybody', why: 'Hardly is already negative, so hardly nobody is a double negative.' },
  { id: 'e083', lv: 3, parts: ['If we', 'loose this game,', 'we will be', 'out of the tournament.'], bad: 1, fix: 'lose this game,', why: 'Lose means to not win. Loose means not tight.' },
  { id: 'e084', lv: 3, parts: ['Jake ran', 'to the store', 'and buys', 'a bag of chips.'], bad: 2, fix: 'and bought', why: 'Ran is past tense, so buys must shift to the past too: bought.' },
  { id: 'e085', lv: 3, parts: ['The coach', 'told my teammate', 'and I', 'to stretch before practice.'], bad: 2, fix: 'and me', why: 'The coach told me, not told I. Me is the object.' },
  { id: 'e086', lv: 3, parts: ['Mathematics', 'is', 'my favorite subject', 'this year.'], bad: 4, fix: '', why: 'No error. Mathematics ends in s, but it is one subject, so is is correct.' },
  { id: 'e087', lv: 3, parts: ['Our principle', 'announced', 'that school would close', 'early because of snow.'], bad: 0, fix: 'Our principal', why: 'The principal is the head of a school. A principle is a rule or belief.' },
  { id: 'e088', lv: 3, parts: ['Its', 'been raining', 'for three', 'days straight.'], bad: 0, fix: 'It\'s', why: 'It\'s here means "it has": it has been raining. Its shows ownership.' },
  { id: 'e089', lv: 3, parts: ['The fans', 'went wild', 'when the home team', 'scores in overtime.'], bad: 3, fix: 'scored in overtime.', why: 'Went is past tense, so scores must shift to scored.' },
  { id: 'e090', lv: 3, parts: ['Of my two', 'older brothers,', 'Max is', 'the tallest.'], bad: 3, fix: 'the taller.', why: 'With only two brothers, use the comparative form taller, not tallest.' },
  { id: 'e091', lv: 3, parts: ['The movie', 'was so good', 'that I', 'seen it twice.'], bad: 3, fix: 'saw it twice.', why: 'The past tense of see is saw. Seen needs a helper like have.' },
  { id: 'e092', lv: 3, parts: ['A herd of', 'elephants', 'was', 'crossing the river.'], bad: 4, fix: '', why: 'No error. The subject is herd, which is one group, so was is correct.' },
  { id: 'e093', lv: 3, parts: ['My friend', 'and his', 'cousin', 'was late for the bus.'], bad: 3, fix: 'were late for the bus.', why: 'My friend and his cousin are two people, so the verb is were.' },
  { id: 'e094', lv: 3, parts: ['The wizard', 'should have', 'went', 'home before midnight.'], bad: 2, fix: 'gone', why: 'After should have, use the past participle: go, went, gone.' },
  { id: 'e095', lv: 3, parts: ['Us kids', 'wanted', 'to stay up', 'for the meteor shower.'], bad: 0, fix: 'We kids', why: 'Drop kids and test it: "We wanted to stay up," not "Us wanted."' },
  { id: 'e096', lv: 3, parts: ['The coach gave', 'the trophy', 'to we players', 'at the banquet.'], bad: 2, fix: 'to us players', why: 'After the preposition to, use the object pronoun us. Test it: "to us."' },
  { id: 'e097', lv: 3, parts: ['None of the', 'cake', 'was', 'left after the party.'], bad: 4, fix: '', why: 'No error. None refers to cake, which you cannot count, so was is correct.' },
  { id: 'e098', lv: 3, parts: ['Everyone', 'accept Jordan', 'remembered', 'to bring a permission slip.'], bad: 1, fix: 'except Jordan', why: 'Except means "but not." Accept means to take or agree to something.' },
  { id: 'e099', lv: 3, parts: ['Riding', 'a bike', 'without a helmet', 'is dangerous.'], bad: 4, fix: '', why: 'No error. The subject is riding (one activity), so is is correct.' },
  { id: 'e100', lv: 3, parts: ['The cheetah', 'is the fastest', 'land animal,', 'it can run seventy miles per hour.'], bad: 2, fix: 'land animal;', why: 'Two complete sentences joined by a comma make a comma splice. Use a semicolon.' },
  { id: 'e101', lv: 3, parts: ['I', 'can\'t hardly', 'wait for', 'summer vacation!'], bad: 1, fix: 'can hardly', why: 'Hardly is already negative, so can\'t hardly is a double negative.' },
  { id: 'e102', lv: 3, parts: ['The team\'s new uniforms', 'looks', 'awesome', 'under the lights.'], bad: 1, fix: 'look', why: 'The subject is uniforms (plural), not team, so the verb is look.' },
  { id: 'e103', lv: 3, parts: ['Our dog', 'sets', 'by the door', 'every afternoon.'], bad: 1, fix: 'sits', why: 'Sit means to be seated. Set means to put something somewhere.' },
  { id: 'e104', lv: 3, parts: ['Neither the pizza', 'nor the tacos', 'is', 'ready yet.'], bad: 2, fix: 'are', why: 'With neither/nor, the verb agrees with the closer subject. Tacos is plural, so are.' },
  { id: 'e105', lv: 3, parts: ['They', 'did the project', 'theirselves', 'without any help.'], bad: 2, fix: 'themselves', why: 'The correct word is themselves. Theirselves is not standard English.' },

  // ===== Level 4 (grade 7) =====
  { id: 'e106', lv: 4, parts: ['Neither the coach', 'nor the players', 'was', 'happy with the referee\'s call.'], bad: 2, fix: 'were', why: 'With neither/nor, the verb agrees with the closer subject. Players is plural, so were.' },
  { id: 'e107', lv: 4, parts: ['The list of', 'chores', 'on the fridge', 'are getting longer every week.'], bad: 3, fix: 'is getting longer every week.', why: 'The subject is list (singular). Chores is inside a phrase and does not count.' },
  { id: 'e108', lv: 4, parts: ['Give the extra tickets', 'to whoever', 'wants', 'them.'], bad: 4, fix: '', why: 'No error. Whoever is the subject of wants (he wants them), so whoever is right, even after to.' },
  { id: 'e109', lv: 4, parts: ['The coach', 'will give', 'a medal to', 'whomever finishes first.'], bad: 3, fix: 'whoever finishes first.', why: 'The pronoun is the subject of finishes (he finishes), so use whoever.' },
  { id: 'e110', lv: 4, parts: ['The ancient pharaohs', 'were buried', 'with gold, jewels, and food,', 'they believed they would need them in the afterlife.'], bad: 2, fix: 'with gold, jewels, and food because', why: 'Two complete sentences joined by only a comma make a comma splice. Because links them correctly.' },
  { id: 'e111', lv: 4, parts: ['If I', 'was', 'a professional gamer,', 'I would stream every night.'], bad: 1, fix: 'were', why: 'For an imaginary situation, formal English uses were: "If I were."' },
  { id: 'e112', lv: 4, parts: ['Everyone except', 'Liam and I', 'got', 'a ticket to the concert.'], bad: 1, fix: 'Liam and me', why: 'Except is a preposition, so it takes the object pronoun me.' },
  { id: 'e113', lv: 4, parts: ['The crowd', 'had already', 'began', 'to leave before the final whistle.'], bad: 2, fix: 'begun', why: 'After had, use the past participle: begin, began, begun.' },
  { id: 'e114', lv: 4, parts: ['Having finished', 'his homework,', 'Owen', 'finally turned on the game.'], bad: 4, fix: '', why: 'No error. The opening phrase describes Owen, and Owen comes right after the comma.' },
  { id: 'e115', lv: 4, parts: ['Walking through', 'the haunted house,', 'a skeleton', 'jumped out at us.'], bad: 0, fix: 'As we walked through', why: 'As written, the skeleton is the one walking through the house. The opening must not dangle.' },
  { id: 'e116', lv: 4, parts: ['There\'s', 'three reasons', 'why I love', 'basketball.'], bad: 0, fix: 'There are', why: 'There\'s means "there is," but the subject is three reasons (plural). Use There are.' },
  { id: 'e117', lv: 4, parts: ['Either of', 'the two snacks', 'is', 'fine with me.'], bad: 4, fix: '', why: 'No error. Either is singular, so is is correct.' },
  { id: 'e118', lv: 4, parts: ['The detective', 'implied', 'from the clues', 'that the butler was guilty.'], bad: 1, fix: 'inferred', why: 'To infer is to figure something out. To imply is to hint at it. The detective figured it out.' },
  { id: 'e119', lv: 4, parts: ['Did the cold weather', 'have', 'any affect', 'on the race?'], bad: 2, fix: 'any effect', why: 'Here the word is a noun (a result), so it is effect.' },
  { id: 'e120', lv: 4, parts: ['Lying', 'on the beach', 'all day', 'gave me a sunburn.'], bad: 4, fix: '', why: 'No error. Lying means resting. Laying would need an object, like laying a towel down.' },
  { id: 'e121', lv: 4, parts: ['Yesterday', 'the hen', 'lay', 'six eggs.'], bad: 2, fix: 'laid', why: 'The hen put the eggs down, so the verb is lay, and its past tense is laid.' },
  { id: 'e122', lv: 4, parts: ['The bus driver', 'gave', 'Noah and myself', 'a warning.'], bad: 2, fix: 'Noah and me', why: 'Myself is only used when I already appears in the sentence. Here the object is me.' },
  { id: 'e123', lv: 4, parts: ['The team', 'that has won', 'the most games', 'get to host the final.'], bad: 3, fix: 'gets to host the final.', why: 'The subject is team (singular). Games is part of the middle phrase, so gets.' },
  { id: 'e124', lv: 4, parts: ['The game', 'cost', 'less than', 'fifty dollars.'], bad: 4, fix: '', why: 'No error. An amount of money is treated as one quantity, so less than is correct.' },
  { id: 'e125', lv: 4, parts: ['The captain, along with', 'his crew,', 'are', 'ready for takeoff.'], bad: 2, fix: 'is', why: 'Along with does not join subjects the way and does. The subject is captain, so is.' },
  { id: 'e126', lv: 4, parts: ['My older brother', 'is', 'real', 'good at chess.'], bad: 2, fix: 'really', why: 'Real is an adjective. To describe the adjective good, use the adverb really.' },
  { id: 'e127', lv: 4, parts: ['The flag', 'had', 'been rose', 'before the ceremony began.'], bad: 2, fix: 'been raised', why: 'Someone lifted the flag, so the verb is raise: had been raised. Rose is the past of rise.' },
  { id: 'e128', lv: 4, parts: ['I would rather', 'play outside', 'then', 'sit inside all day.'], bad: 2, fix: 'than', why: 'Rather...than is a comparison, so use than.' },
  { id: 'e129', lv: 4, parts: ['Marco is', 'one of those players', 'who', 'always arrive early.'], bad: 4, fix: '', why: 'No error. Who refers to players (plural), not to one, so arrive is correct.' },
  { id: 'e130', lv: 4, parts: ['When', 'the referee', 'blew the whistle,', 'the players stop running.'], bad: 3, fix: 'the players stopped running.', why: 'Blew is past tense, so stop must shift to stopped.' },
  { id: 'e131', lv: 4, parts: ['My mom', 'complemented', 'my drawing', 'of a dragon.'], bad: 1, fix: 'complimented', why: 'A compliment is praise. A complement is something that completes or goes well with something else.' },
  { id: 'e132', lv: 4, parts: ['The Smiths\'', 'dog', 'barks', 'all night.'], bad: 4, fix: '', why: 'No error. The dog belongs to the whole family (the Smiths), so the apostrophe goes after the s.' },
  { id: 'e133', lv: 4, parts: ['Irregardless', 'of the weather,', 'the game', 'will go on.'], bad: 0, fix: 'Regardless', why: 'Irregardless is a double negative (ir- and -less). Standard English uses regardless.' },
  { id: 'e134', lv: 4, parts: ['The skateboarder', 'landed', 'the trick', 'perfect.'], bad: 3, fix: 'perfectly.', why: 'The word tells how he landed it, so it must be the adverb perfectly.' },
  { id: 'e135', lv: 4, parts: ['A pair', 'of socks', 'were', 'missing from the dryer.'], bad: 2, fix: 'was', why: 'The subject is pair (one pair), not socks. Use was.' },
  { id: 'e136', lv: 4, parts: ['By the time', 'we got to the theater,', 'the movie', 'already started.'], bad: 3, fix: 'had already started.', why: 'The movie started before we got there, so use the past perfect: had started.' },
  { id: 'e137', lv: 4, parts: ['The trophy', 'was given', 'to Ava and he', 'for their science fair project.'], bad: 2, fix: 'to Ava and him', why: 'After the preposition to, use the object pronoun him.' },
  { id: 'e138', lv: 4, parts: ['My brother', 'is', 'one of the', 'most fastest runners in the state.'], bad: 3, fix: 'fastest runners in the state.', why: 'Fastest already means "most fast." Do not use both.' },
  { id: 'e139', lv: 4, parts: ['The snow', 'was so deep', 'that the bus', 'could\'nt get through.'], bad: 3, fix: 'couldn\'t get through.', why: 'The apostrophe replaces the missing letter o in not: could + n\'t = couldn\'t.' },
  { id: 'e140', lv: 4, parts: ['We need', 'to leave', 'right now,', 'otherwise, we will miss the train.'], bad: 2, fix: 'right now;', why: 'Otherwise is not a joining word, so a comma before it makes a comma splice. Use a semicolon.' },

  // ===== Level 5 (grades 7-8) =====
  { id: 'e141', lv: 5, parts: ['The quality of', 'the paintings', 'in the castle', 'were remarkable.'], bad: 3, fix: 'was remarkable.', why: 'The subject is quality (singular). Paintings and castle are inside phrases.' },
  { id: 'e142', lv: 5, parts: ['The knight', 'whom everyone believed', 'was a traitor', 'turned out to be a hero.'], bad: 1, fix: 'who everyone believed', why: 'The pronoun is the subject of was. Remove "everyone believed" and you get "who was a traitor."' },
  { id: 'e143', lv: 5, parts: ['The prize will go', 'to whomever', 'the judges', 'select.'], bad: 4, fix: '', why: 'No error. The pronoun is the object of select (the judges select him), so whomever is correct.' },
  { id: 'e144', lv: 5, parts: ['Not only', 'the captain', 'but also', 'the players was exhausted.'], bad: 3, fix: 'the players were exhausted.', why: 'With not only/but also, the verb agrees with the closer subject. Players is plural, so were.' },
  { id: 'e145', lv: 5, parts: ['The phenomenon', 'of the northern lights', 'are caused', 'by particles from the sun.'], bad: 2, fix: 'is caused', why: 'Phenomenon is singular (the plural is phenomena), so is caused.' },
  { id: 'e146', lv: 5, parts: ['Neither', 'the Romans nor the Greeks', 'was able', 'to conquer that tribe.'], bad: 2, fix: 'were able', why: 'The closer subject is Greeks (plural), so the verb is were.' },
  { id: 'e147', lv: 5, parts: ['If the volcano', 'were', 'to erupt today,', 'the town would be evacuated.'], bad: 4, fix: '', why: 'No error. For an imaginary situation, use were, even with a singular subject like volcano.' },
  { id: 'e148', lv: 5, parts: ['The explorers', 'had went', 'farther north', 'than anyone before them.'], bad: 1, fix: 'had gone', why: 'After had, use the past participle gone. Went is the simple past.' },
  { id: 'e149', lv: 5, parts: ['Sitting', 'quietly', 'in the back,', 'the lecture bored the students.'], bad: 3, fix: 'the students were bored by the lecture.', why: 'The opening phrase must describe what comes right after it. The lecture was not sitting in the back.' },
  { id: 'e150', lv: 5, parts: ['My grandfather', 'has', 'lain', 'in the hammock all afternoon.'], bad: 4, fix: '', why: 'No error. Lain is the past participle of lie (to rest): lie, lay, lain.' },
  { id: 'e151', lv: 5, parts: ['The hikers', 'had laid', 'down to rest', 'when the bear appeared.'], bad: 1, fix: 'had lain', why: 'The hikers were resting, so the verb is lie. Its past participle is lain.' },
  { id: 'e152', lv: 5, parts: ['Of all the', 'Greek gods,', 'Zeus was', 'the more powerful.'], bad: 3, fix: 'the most powerful.', why: 'Comparing more than two things takes the superlative: most.' },
  { id: 'e153', lv: 5, parts: ['The coach', 'insisted', 'that every player', 'runs two extra laps.'], bad: 3, fix: 'run two extra laps.', why: 'After insisted that, formal English uses the base form of the verb: run.' },
  { id: 'e154', lv: 5, parts: ['The amount of', 'people', 'at the stadium', 'was incredible.'], bad: 0, fix: 'The number of', why: 'People can be counted, so use number. Amount is for things you cannot count.' },
  { id: 'e155', lv: 5, parts: ['The ship', 'sunk', 'in less than', 'three hours.'], bad: 1, fix: 'sank', why: 'The simple past of sink is sank. Sunk needs a helper, as in "has sunk."' },
  { id: 'e156', lv: 5, parts: ['Mount Everest', 'is taller', 'than any', 'mountain in the world.'], bad: 2, fix: 'than any other', why: 'Everest is a mountain in the world, so it cannot be taller than itself. Add other.' },
  { id: 'e157', lv: 5, parts: ['Her', 'and her teammates', 'practiced', 'every morning before school.'], bad: 0, fix: 'She', why: 'The pronoun is part of the subject. Test it: "She practiced," not "Her practiced."' },
  { id: 'e158', lv: 5, parts: ['A number of', 'students', 'have', 'signed up for the trip.'], bad: 4, fix: '', why: 'No error. A number of means "many," so it takes the plural verb have.' },
  { id: 'e159', lv: 5, parts: ['The general', 'led', 'his army', 'across the river, it was a bold move.'], bad: 3, fix: 'across the river; it was a bold move.', why: 'Two complete sentences joined by a comma make a comma splice. Use a semicolon.' },
  { id: 'e160', lv: 5, parts: ['The tsunami', 'caused', 'alot of', 'damage along the coast.'], bad: 2, fix: 'a lot of', why: 'A lot is always two words. Alot is not a word.' },
  { id: 'e161', lv: 5, parts: ['Whom', 'should I say', 'is', 'calling?'], bad: 0, fix: 'Who', why: 'The pronoun is the subject of is calling. Remove "should I say": "Who is calling?"' },
  { id: 'e162', lv: 5, parts: ['Neither', 'of the answers', 'seem', 'correct to me.'], bad: 2, fix: 'seems', why: 'Neither is singular, so the verb is seems.' },
  { id: 'e163', lv: 5, parts: ['The witness', 'testified', 'that she', 'seen the thief climbing the fence.'], bad: 3, fix: 'saw the thief climbing the fence.', why: 'The simple past of see is saw. Seen needs a helper like had.' },
  { id: 'e164', lv: 5, parts: ['The volcano,', 'who\'s', 'last eruption', 'was in 1980, is still active.'], bad: 1, fix: 'whose', why: 'Whose shows possession and can refer to things. Who\'s means "who is."' },
  { id: 'e165', lv: 5, parts: ['The scientist', 'had studied', 'the comet', 'for ten years before she discovers its tail.'], bad: 3, fix: 'for ten years before she discovered its tail.', why: 'Had studied sets the story in the past, so discovers must be discovered.' },
  { id: 'e166', lv: 5, parts: ['Neither', 'the twins', 'nor', 'their dad know how to swim.'], bad: 3, fix: 'their dad knows how to swim.', why: 'With neither/nor, the verb agrees with the closer subject. Dad is singular, so knows.' },
  { id: 'e167', lv: 5, parts: ['The lead singer', 'and guitarist', 'is', 'my cousin Ryan.'], bad: 4, fix: '', why: 'No error. The lead singer and guitarist is one person (Ryan), so the singular is is correct.' },
  { id: 'e168', lv: 5, parts: ['The alien spaceship', 'landed', 'in a field', 'between Jack\'s farm and our\'s.'], bad: 3, fix: 'between Jack\'s farm and ours.', why: 'Possessive pronouns like ours, yours, and theirs never take an apostrophe.' },
  { id: 'e169', lv: 5, parts: ['The Titanic', 'was', 'considered', 'unsinkable, however it sank on its first voyage.'], bad: 3, fix: 'unsinkable; however, it sank on its first voyage.', why: 'However cannot join two sentences with a comma. Use a semicolon before it and a comma after.' },
  { id: 'e170', lv: 5, parts: ['The more', 'you practice,', 'the more better', 'you will become.'], bad: 2, fix: 'the better', why: 'Better is already a comparative, so more better is a double comparison.' },
  { id: 'e171', lv: 5, parts: ['Ten miles', 'is', 'a long way', 'to hike in one day.'], bad: 4, fix: '', why: 'No error. Ten miles is treated as one distance, so the singular is is correct.' },
  { id: 'e172', lv: 5, parts: ['The ancient', 'Egyptians', 'believed', 'that cats were sacred, so they treated them good.'], bad: 3, fix: 'that cats were sacred, so they treated them well.', why: 'The word tells how they treated the cats, so use the adverb well.' },
  { id: 'e173', lv: 5, parts: ['Being that', 'it was raining,', 'the game', 'was postponed.'], bad: 0, fix: 'Because', why: 'Being that is not standard English. Use because or since.' },
  { id: 'e174', lv: 5, parts: ['The boy', 'who\'s', 'bike was stolen', 'reported it to the police.'], bad: 1, fix: 'whose', why: 'The bike belongs to the boy, so use whose. Who\'s means "who is."' },
  { id: 'e175', lv: 5, parts: ['Seventy percent', 'of the Earth\'s surface', 'are', 'covered by water.'], bad: 2, fix: 'is', why: 'With percent, the verb agrees with what follows of. Surface is singular, so is.' },
];
