// Reading: passages for US grades 5-8, each with 3 questions. why = where the answer is in the text.
// Levels are measured with Flesch-Kincaid: lv1 5.0-6.0, lv2 6.0-7.0, lv3 6.8-7.8, lv4 7.8-8.8, lv5 8.8-10.0.
export const READING = [
  // ---------- Level 1: grade 5, 220-280 words ----------
  {
    id: 'r01', lv: 1, title: "The Case of the Vanishing Cookies",
    text: "Every Saturday, Grandma Rosa baked a tray of oatmeal cookies and left it on the kitchen windowsill to cool. Nobody in the family would ever dare to interrupt this tradition. So when Nico got home from soccer practice and found the tray completely empty, he knew at once that a crime had been committed.\n\nNico considered himself the most observant detective on Maple Street, although, to be fair, he was also the only one. He opened his notebook and recorded three clues. There were crumbs scattered near the back door. There was a small, muddy print on the windowsill. And his little sister, Ana, had a suspicious brown smear on her chin.\n\n'Ana did it,' Nico announced confidently.\n\nAna rolled her eyes. 'That's chocolate from my candy bar. I would never eat oatmeal cookies. They taste like cardboard.'\n\nNico frowned, because he had to admit that she was right. Ana had refused oatmeal in every form since she was three years old.\n\nHe studied the print again. It was far too tiny to belong to Biscuit, their huge, lazy old dog. Besides, Biscuit was snoring under the table. Following the trail of crumbs, Nico crossed the yard until he reached the oak tree beside the fence.\n\nPerched on a branch sat a plump gray squirrel, clutching a cookie in its paws and nibbling frantically. Behind it, stuffed into a hollow in the trunk, Nico counted six more cookies.\n\n'Case closed,' Nico declared. Then he marched inside to make a recommendation: next Saturday, the cookies should cool somewhere that squirrels could not reach.",
    qs: [
      { q: "Why does Nico decide that Ana is NOT the thief?", a: "She has refused to eat oatmeal for years.", wrong: ["She was at soccer practice with Nico.", "She had no crumbs anywhere on her.", "She was asleep under the kitchen table."], why: "Ana says oatmeal cookies taste like cardboard, and the text confirms she 'had refused oatmeal in every form since she was three years old.'" },
      { q: "As used in paragraph 2, what does 'observant' most likely mean?", a: "good at noticing small details", wrong: ["quick at running from place to place", "polite to people who are older", "afraid of breaking the family rules"], why: "Nico proves he is observant by spotting and recording three small clues: crumbs, a muddy print, and a smear on Ana's chin." },
      { q: "What can the reader infer from Nico's recommendation at the end?", a: "The windowsill made the cookies easy for the squirrel to reach.", wrong: ["Grandma should stop baking oatmeal cookies on Saturdays.", "The squirrel will be punished for stealing the cookies.", "Ana should be kept out of the kitchen from now on."], why: "He suggests the cookies cool 'somewhere that squirrels could not reach,' which implies the windowsill was within the squirrel's reach." },
    ],
  },
  {
    id: 'r02', lv: 1, title: "The Toughest Animal on Earth",
    text: "Meet one of the toughest creatures on the planet. It is usually less than a millimeter long, so you would need a microscope to see it clearly. It has eight stubby legs with tiny claws on the ends. Scientists call it a tardigrade. But because it lumbers along like a chubby little bear, most people call it a water bear.\n\nTardigrades live almost everywhere. You can find them in damp moss, in sand dunes, on mountaintops, and on the deep ocean floor. If you scooped up some moss from your backyard and looked at it under a microscope, you might find a few of them.\n\nWhat makes water bears famous is their remarkable ability to survive. When their home dries out, a tardigrade pulls in its legs and curls into a shriveled ball called a tun. Then its body slows down until it has almost stopped. In this state, it can endure freezing cold, intense heat, and years without water. When water finally returns, the tiny animal swells up, stretches its legs, and walks away as if nothing had happened.\n\nIn 2007, researchers tested this toughness in an extreme way. They attached dried tardigrades to the outside of a spacecraft, where there was no air and no shield from harsh sunlight. Many of them survived the trip. Some later laid eggs that hatched into healthy babies.\n\nScientists now study how water bears protect their bodies. They hope the answers might someday help keep medicines safe without a fridge. Water bears are not superheroes, but they may be the closest thing nature has made.",
    qs: [
      { q: "What is the main idea of the passage?", a: "Tardigrades are tiny animals that can survive extreme conditions.", wrong: ["Tardigrades are small bears that live in moss and sand dunes.", "Scientists sent tardigrades on a trip into space in 2007.", "Tardigrades can only be found by using a strong microscope."], why: "Most of the passage describes how water bears survive drying out, cold, heat, and even space." },
      { q: "As used in paragraph 3, what does 'endure' mean?", a: "to survive or put up with", wrong: ["to escape or run away from", "to search for or discover", "to cause or create on purpose"], why: "The tardigrade 'can endure freezing cold, intense heat, and years without water' and then walks away, so it survives them." },
      { q: "Why did researchers attach tardigrades to the outside of a spacecraft?", a: "to test whether they could survive harsh space conditions", wrong: ["to help the spacecraft collect samples of moss", "to keep the tiny animals safe from freezing", "to find out how fast tardigrades can travel"], why: "The text says researchers 'tested this toughness in an extreme way' by placing them where there was 'no air and no shield from harsh sunlight.'" },
    ],
  },
  {
    id: 'r03', lv: 1, title: "The Walk That Made Velcro",
    text: "In 1941, a Swiss engineer named George de Mestral took his dog for a hike in the mountains. When they got home, both of them were covered in burrs, the prickly seed pods of a plant called burdock. Most people would have simply picked them off and thrown them away. De Mestral, however, became curious about why they clung so stubbornly.\n\nHe put a burr under a microscope. He saw that it was covered in hundreds of tiny hooks. These hooks snagged on anything with a loop, such as the threads in his pants or his dog's fur. De Mestral wondered if people could make a fastener that worked the same way.\n\nTurning that idea into a real product was very hard. For about ten years, he experimented with different materials. Cotton was too soft and wore out quickly. Eventually, he discovered that nylon could form strong, durable hooks. One strip of fabric held the hooks, and the other held soft loops. Pressed together, they gripped tightly. Pulled apart, they made a familiar ripping sound.\n\nHe called his invention Velcro, combining two French words: velours, meaning velvet, and crochet, meaning hook. At first, many people considered it ugly and cheap-looking. Then NASA began using it to keep tools and food from floating away inside spacecraft. Suddenly it seemed exciting. Today you can find Velcro on shoes, jackets, and backpacks. It all started because one man refused to ignore an annoying walk in the woods.",
    qs: [
      { q: "Which detail best shows that de Mestral was persistent?", a: "He experimented with materials for about ten years.", wrong: ["He took his dog for a hike in the mountains.", "He combined two French words to name Velcro.", "He looked at a single burr under a microscope."], why: "Persistence means not giving up, and the text says that 'for about ten years, he experimented with different materials.'" },
      { q: "As used in paragraph 3, what does 'durable' mean?", a: "strong and long-lasting", wrong: ["soft and easy to bend", "cheap and quick to make", "sticky and hard to remove"], why: "Cotton 'wore out quickly,' but nylon made 'strong, durable hooks,' so durable means it does not wear out." },
      { q: "Why does the author mention NASA in the last paragraph?", a: "to explain how Velcro became popular", wrong: ["to show that de Mestral worked for NASA", "to describe how Velcro was first invented", "to prove that Velcro is ugly and cheap"], why: "People first thought Velcro was ugly, but after NASA used it, 'Suddenly it seemed exciting.'" },
    ],
  },
  {
    id: 'r04', lv: 1, title: "The FoldBot 3000",
    text: "Jada had a serious problem, and its name was laundry. Every Sunday, her mother made her fold a huge mountain of clean clothes. And every Sunday, Jada grumbled that there had to be a more efficient method.\n\nSo she invented one. She used an old remote-control car, two kitchen spatulas, and an alarming amount of tape. She named her robot the FoldBot 3000, even though there had never been a FoldBot 1, 2, or 2,999.\n\nOn Sunday morning, Jada set the FoldBot beside the laundry basket and pressed the big red button. The machine whirred to life. Its spatula arms flapped, seized a T-shirt, and folded it into a flawless square.\n\n'It works!' Jada shouted triumphantly.\n\nThen it folded a sock, and then a towel. Then it folded the newspaper that Dad was reading, right out of his hands.\n\n'Jada,' Dad said slowly.\n\nThe FoldBot rolled across the living room, folding a pillowcase, a dish towel, and the corner of the rug. Then it turned toward Pickles, the cat, who was napping peacefully in a warm patch of sunlight.\n\nJada dove across the carpet and slammed the red button just in time. Pickles opened one eye, yawned, and went back to sleep, apparently unaware of her narrow escape.\n\nMom silently surveyed the neat stack of shirts, the crumpled newspaper, the folded rug, and finally her daughter.\n\n'Version two,' Jada announced quickly, before anyone else could say a word, 'will have a stop button that works from across the room.'",
    qs: [
      { q: "Which sentence best states a theme of the story?", a: "Inventions often need to be improved after they are tested.", wrong: ["Cats should never be allowed anywhere near the laundry.", "Robots can do every household chore better than people.", "Parents should always fold the laundry for their kids."], why: "The FoldBot works at first but goes out of control, and Jada ends by planning 'Version two' with a better stop button." },
      { q: "Why does the author say there had never been a FoldBot 1, 2, or 2,999?", a: "to show that the robot's big name is a joke", wrong: ["to show that Jada built many robots before", "to explain exactly how the robot folds clothes", "to show that Dad helped Jada build the robot"], why: "The name FoldBot 3000 sounds like the newest of many models, but this is Jada's very first one, which makes the name funny." },
      { q: "Why does Jada speak 'before anyone else could say a word'?", a: "She wants to show she has a plan before she gets in trouble.", wrong: ["She is worried that the cat will wake up and run away.", "She wants Dad to go back to reading his newspaper.", "She thinks Mom is about to praise the folded shirts."], why: "Mom is silently looking at the mess, so Jada quickly offers a fix ('Version two') to head off a scolding." },
    ],
  },
  {
    id: 'r05', lv: 1, title: "Sea Otter Tricks",
    text: "Sea otters live along the chilly Pacific coast of North America. They rely on a clever collection of tricks to survive.\n\nUnlike seals and whales, sea otters do not have a thick layer of blubber, or fat, to keep them warm. Instead, they have the densest fur of any animal on Earth. A single square inch of sea otter fur can contain up to a million hairs. That is more than most people have on their entire head. Their fur only works when it is clean and fluffy. So otters spend hours each day grooming it, rubbing and combing it to trap tiny air bubbles that hold in heat. If their fur becomes coated in oil from a spill, it can no longer protect them, and the otter may freeze.\n\nSea otters are also skilled tool users. An otter will dive to the sea floor, collect a clam or a sea urchin, and bring up a flat rock as well. Floating on its back, it balances the rock on its chest and pounds the shell against it until the shell cracks. Some otters even store a favorite rock in a loose pocket of skin under their arm.\n\nWhen it is time to sleep, sea otters wrap themselves in long strands of kelp so they do not drift away with the current. Mothers often float with their pups resting on their bellies. A group of floating otters is called a raft. That seems like a fitting name for animals that spend almost their entire lives on the water.",
    qs: [
      { q: "Based on the passage, why is an oil spill especially dangerous for sea otters?", a: "Oily fur cannot keep them warm, and they have no blubber.", wrong: ["Oil makes it harder for otters to find flat rocks.", "Oil causes the kelp to break so otters drift away.", "Oil makes the clams and urchins taste much worse."], why: "Otters have no blubber and depend on clean fur to hold in heat. If the fur is coated in oil, 'it can no longer protect them.'" },
      { q: "As used in the last paragraph, what does 'fitting' mean?", a: "right for the situation", wrong: ["tight around the body", "strange and confusing", "used for a long time"], why: "A raft floats on water, and otters spend their lives on the water, so the name suits them well." },
      { q: "Which detail best supports the idea that sea otters are tool users?", a: "They crack shells open by pounding them on rocks.", wrong: ["They wrap themselves in kelp while they sleep.", "They have up to a million hairs per square inch.", "They float with their pups resting on their bellies."], why: "Paragraph 3 begins 'Sea otters are also skilled tool users' and describes pounding shells against a rock." },
    ],
  },

  // ---------- Level 2: grades 5-6, 260-320 words ----------
  {
    id: 'r06', lv: 2, title: "The Punch of the Mantis Shrimp",
    text: "If you were a crab living on a coral reef, the last creature you would want to meet is a mantis shrimp. Despite its name, it is neither a shrimp nor a praying mantis. It is a brightly colored crustacean, usually about as long as a human hand. It also has one of the fastest strikes in the animal kingdom.\n\nSome mantis shrimp, known as smashers, keep a pair of club-shaped limbs folded beneath their bodies. When they attack, these clubs shoot forward at roughly 50 miles per hour. The strike is so rapid that the water in front of the club cannot keep up, and tiny bubbles form. When those bubbles collapse, they release a second burst of force, along with heat and a faint flash of light. Consequently, a snail or crab is struck twice in a fraction of a second. In aquariums, large mantis shrimp have occasionally cracked the glass walls of their tanks.\n\nTheir eyes are equally unusual. Humans have three types of color-sensing cells, while mantis shrimp have between twelve and sixteen. Each eye sits on its own stalk. The animal can look up with one eye and sideways with the other. Surprisingly, experiments suggest that mantis shrimp are not especially good at telling similar colors apart. Scientists think their eyes may be built for speed rather than detail. This would let them recognize colors instantly instead of carefully comparing them.\n\nEngineers have also studied the smasher's club. It can survive thousands of violent blows without breaking. By copying its layered structure, they hope to build lighter, tougher materials for helmets and airplanes.",
    qs: [
      { q: "As used in paragraph 2, the word 'consequently' signals that the next idea is...", a: "a result of what was just described", wrong: ["an example that disagrees with it", "a comparison with a different animal", "a question the scientists cannot answer"], why: "The double hit happens because of the collapsing bubbles described just before, so 'consequently' introduces a result." },
      { q: "What can the reader infer from paragraph 3 about the mantis shrimp's eyes?", a: "Having more color cells does not guarantee better color vision.", wrong: ["Mantis shrimp see colors in exactly the same way humans do.", "Mantis shrimp can only see in black, white, and shades of gray.", "Mantis shrimp must keep both eyes pointed in one direction."], why: "They have up to sixteen color cells compared with our three, yet they 'are not especially good at telling similar colors apart.'" },
      { q: "What is the author's purpose in the last paragraph?", a: "to show how people hope to use what they learn", wrong: ["to describe the mantis shrimp's bright colors", "to warn readers never to touch a mantis shrimp", "to explain why the shrimp's bubbles make light"], why: "It explains that engineers are copying the club's structure 'to build lighter, tougher materials for helmets and airplanes.'" },
    ],
  },
  {
    id: 'r07', lv: 2, title: "Fog on Pine Lake",
    text: "Owen and his older cousin Tess had paddled their canoe to the far shore of Pine Lake, where the fish supposedly bit better. By the time they turned back, a dense white fog had drifted across the water, so thick that Owen could barely make out Tess's shape at the front of the canoe.\n\n'Which way is camp?' asked Tess, whose voice, usually so confident, now sounded small.\n\nOwen felt his heart hammering, because everything around them looked identical: gray water, gray air, gray nothing. Then he recalled something his grandfather had taught him the previous summer, while they were fishing on this same lake. Sound travels well across water, his grandfather had said, and when you are lost, you should stop and listen before you move.\n\n'Stop paddling,' Owen said, trying to sound calmer than he felt.\n\nThey sat motionless while water lapped gently against the hull. A loon called somewhere to their left. Then, faintly, Owen detected something else: a steady metallic clang, repeating again and again.\n\n'The dinner bell,' he whispered. Every evening at six, Mr. Alvarez rang the iron bell outside the camp kitchen, though usually only a few times.\n\nThey aimed the canoe toward the sound and paddled cautiously, pausing every few strokes to make sure they were still heading the right way. Gradually the clanging grew louder, until a dark shape emerged from the fog: the wooden dock, with Mr. Alvarez standing at the very end, still swinging the bell rope.\n\n'I kept ringing once the fog rolled in,' he said, rubbing his aching arm. 'Figured somebody might need it.'\n\nTess scrambled out and hugged him. Owen remained in the canoe a moment longer, listening to the quiet, and decided he would call his grandfather that night.",
    qs: [
      { q: "Which sentence best states the theme of the story?", a: "Staying calm and using what you have learned can solve a problem.", wrong: ["Younger cousins should never go fishing far from their camp.", "Fog on a lake always clears up if you wait long enough.", "Loons can help lost people find their way back home."], why: "Owen's heart was hammering, but he remembered his grandfather's advice, stopped, listened, and found the way back." },
      { q: "Why does the author mention that Mr. Alvarez usually rang the bell 'only a few times'?", a: "to show that his long ringing was unusual and on purpose", wrong: ["to show that dinner at the camp was very late that night", "to show that the iron bell was old and hard to ring", "to show that the bell could be heard from far away"], why: "He rang far longer than usual, and he explains, 'I kept ringing once the fog rolled in. Figured somebody might need it.'" },
      { q: "Why does Owen most likely decide to call his grandfather?", a: "His grandfather's advice helped him find the way back.", wrong: ["He wants to tell him about the fish they caught.", "He wants his grandfather to drive him home early.", "He wants to complain about Tess being so scared."], why: "Owen got back safely by following what his grandfather taught him: stop and listen before you move." },
    ],
  },
  {
    id: 'r08', lv: 2, title: "Wilma Rudolph Runs",
    text: "When Wilma Rudolph was born in Tennessee in 1940, she weighed only four and a half pounds. She was the twentieth of twenty-two children. She was also often sick. At age four, she contracted polio, a disease that left her left leg weak and twisted. Doctors predicted that she might never walk normally.\n\nHer family, however, refused to accept that prediction. Every week, Wilma and her mother rode a bus about fifty miles to a hospital in Nashville. It was one of the nearest places that would treat Black patients. At home, her brothers and sisters took turns massaging her leg several times a day. For years, Wilma wore a heavy metal brace. Around age twelve, she finally took it off for good.\n\nOnce she could run, she seemed determined to make up for lost time. She became a basketball star in high school, and a college track coach named Ed Temple noticed her remarkable speed. At just sixteen, she earned a bronze medal in a relay race at the 1956 Olympics.\n\nFour years later, at the 1960 Olympics in Rome, Rudolph became the first American woman to win three gold medals in track and field at a single Olympics. Reporters around the world called her the fastest woman alive.\n\nWhen she returned home, her town of Clarksville planned a parade in her honor. At the time, much of the South was segregated, meaning that Black and white people were kept apart by law. Rudolph announced that she would not attend unless the celebration was open to everyone. Consequently, the parade and the banquet that followed became the first integrated events in the town's history.",
    qs: [
      { q: "As used in paragraph 1, what does 'contracted' mean?", a: "caught or came down with", wrong: ["signed or agreed to", "shrank or grew smaller", "cured or recovered from"], why: "She 'contracted polio, a disease' that weakened her leg, so she caught the disease." },
      { q: "Which detail best supports the idea that Wilma's family was determined to help her?", a: "Her siblings massaged her leg several times a day.", wrong: ["She was the twentieth of twenty-two children.", "A college coach noticed her remarkable speed.", "She earned a bronze medal at the age of sixteen."], why: "Paragraph 2 opens with her family refusing to accept the doctors' prediction, then describes her brothers and sisters massaging her leg every day." },
      { q: "What does Rudolph's decision about the parade suggest about her?", a: "She used her fame to push for fairness.", wrong: ["She did not enjoy parades or crowds.", "She wanted the parade to be in Rome.", "She was too tired to celebrate at all."], why: "In a segregated town, she refused to attend unless the event was 'open to everyone,' and it became the town's first integrated celebration." },
    ],
  },
  {
    id: 'r09', lv: 2, title: "The Missing Trophy",
    text: "On Monday morning, the glass case outside the principal's office was empty, because the gold trophy from the state spelling bee, the pride of Hillside Middle School, had vanished.\n\nBy lunchtime, rumors were spreading faster than the cafeteria could serve pizza. Some students blamed the team from Riverview, which had lost the final round. Others whispered about Mr. Pike, the custodian, simply because he carried keys to every door. Priya, who had won the bee, felt slightly sick, since technically it was her trophy.\n\nRather than join the gossip, Priya decided to investigate. She noticed immediately that the lock on the case was undamaged, which meant that whoever had opened it had used a key. She also discovered a small white card wedged behind the case that read 'Order 4471, ready Friday.'\n\nWhen Priya showed the card to her best friend, Dmitri, he frowned and asked what kind of order it could be.\n\nAfter school, the two of them walked along Main Street, peering into every shop window. At the third store, Gold Star Engraving, Priya stopped abruptly, because on the counter, gleaming under the lights, sat the missing trophy.\n\nThe man behind the counter smiled when he noticed them. 'Your principal dropped this off on Saturday so that I could add a new plate to the base,' he explained. 'I believe it's meant to be a surprise at Friday's assembly.'\n\nHe rotated the trophy so they could read the polished new plate: 'State Champion: Priya Raman.'\n\nPriya laughed so hard that she had to sit down on the shop's front step. Then she thought guiltily about Mr. Pike, whose name had been passed around all day without a shred of evidence. Before they left, she and Dmitri made two promises. They would act completely astonished on Friday, and tomorrow, without spoiling the surprise, they would quietly stop the rumors about Mr. Pike.",
    qs: [
      { q: "Why is the undamaged lock an important clue?", a: "It shows that whoever opened the case had a key.", wrong: ["It proves that the Riverview team took the trophy.", "It shows that the trophy was never in the case.", "It proves that Mr. Pike is the real thief."], why: "The text says the lock was undamaged, 'which meant that whoever had opened it had used a key.' The principal turns out to be that person." },
      { q: "Which phrase from the story best shows that the rumors about Mr. Pike were unfair?", a: "without a shred of evidence", wrong: ["carried keys to every door", "faster than the cafeteria", "peering into every shop window"], why: "His name was 'passed around all day without a shred of evidence,' meaning nobody had any proof against him." },
      { q: "Which sentence best states a theme of the story?", a: "Gathering evidence is wiser than spreading rumors.", wrong: ["Principals should never keep secrets from students.", "Custodians are usually blamed when things go missing.", "Winning a contest always leads to a big surprise."], why: "Everyone else gossips, but Priya investigates, finds the truth, and then decides to stop the unfair rumors." },
    ],
  },
  {
    id: 'r10', lv: 2, title: "The Dance of the Honeybee",
    text: "A honeybee that discovers a field full of flowers faces a challenge. How can she inform the thousands of other bees in her hive where the food is located? She cannot draw a map, and she cannot point. Instead, she dances.\n\nBack inside the dark hive, the forager climbs onto the honeycomb, which hangs straight up and down. There she performs what scientists call the waggle dance. She runs forward in a straight line while vibrating her body rapidly from side to side. Then she circles back to her starting point and repeats the run again and again. Her path traces a pattern shaped roughly like a figure eight.\n\nEvery part of this performance carries information. The angle of the straight run indicates direction, measured in relation to the sun. If she waggles straight up the comb, the flowers lie in the direction of the sun. If she waggles at an angle to the right of straight up, the flowers lie at that same angle to the right of the sun. The duration of the waggle communicates distance: the longer she waggles, the farther away the food is.\n\nThe bees crowding around her cannot see well in the darkness. Instead, they follow the dance by touching her with their antennae, and they smell the scent of the flowers on her body. Then they fly out to locate the food themselves.\n\nAn Austrian scientist named Karl von Frisch spent decades watching bees to decode this language. At first, some experts doubted his conclusions. Eventually his experiments convinced most of them, and in 1973 he shared the Nobel Prize. He had demonstrated that an insect with a brain smaller than a sesame seed could communicate precise directions through movement alone.",
    qs: [
      { q: "As used in paragraph 3, what does 'duration' mean?", a: "how long something lasts", wrong: ["which way something points", "how loud something sounds", "where something takes place"], why: "The text explains that 'the longer she waggles, the farther away the food is,' so duration is about length of time." },
      { q: "Based on the passage, a bee that waggles straight DOWN the comb is most likely telling the others that the food is...", a: "in the direction opposite the sun", wrong: ["in the same direction as the sun", "very close to the entrance of the hive", "at an angle to the right of the sun"], why: "Straight up means toward the sun, so straight down, the opposite direction, means away from the sun." },
      { q: "Why does the author mention that some experts doubted von Frisch?", a: "to show that his discovery was not easy to prove", wrong: ["to show that bees cannot really give directions", "to show that he did not deserve the Nobel Prize", "to show that other scientists found it first"], why: "Experts doubted him until 'eventually his experiments convinced most of them,' which shows the idea needed strong proof." },
    ],
  },

  // ---------- Level 3: grade 6, 300-380 words ----------
  {
    id: 'r11', lv: 3, title: "Apollo 13: A Successful Failure",
    text: "On April 13, 1970, three astronauts were roughly 200,000 miles from Earth, hurtling toward the moon, when they heard a sharp bang. One of the oxygen tanks in the service module had exploded. Moments later, Jack Swigert radioed Mission Control in Houston with a calm understatement: 'Houston, we've had a problem here.'\n\nThe command module, Odyssey, needed that oxygen to make electricity. Now its power was rapidly draining away. The crew, Jim Lovell, Jack Swigert, and Fred Haise, abandoned any hope of a moon landing. Their new mission was simply to survive.\n\nTheir lifeboat became Aquarius, the small lunar module that was supposed to carry two of them to the surface of the moon. It had been designed to support two men for about two days. Now it had to sustain three men for nearly four. To conserve power, the crew shut down almost every system, including the heaters. The cabin grew almost as cold as a refrigerator, and water collected on the walls and windows.\n\nThen a less visible threat emerged. With every breath, the astronauts were breathing out carbon dioxide, a gas that can be deadly at high levels. Aquarius carried filters to absorb the gas, but not nearly enough for three people over four days. Odyssey had plenty of spare filters. However, they were square, while the openings in Aquarius were round. Working around the clock, engineers on the ground designed an adapter. They used only materials they knew were on board, such as plastic bags, cardboard covers, a sock, and duct tape. They then read the instructions to the crew, step by step, over the radio. The carbon dioxide levels began to fall.\n\nOn April 17, the astronauts climbed back into Odyssey, released Aquarius, and plunged through the atmosphere. Millions of people watched anxiously until three orange and white parachutes blossomed above the Pacific Ocean. Lovell later called the flight a 'successful failure,' a phrase that captured both what had been lost and what had been achieved.",
    qs: [
      { q: "Why does the author describe Swigert's message as a 'calm understatement'?", a: "He described a life-threatening emergency in very mild words.", wrong: ["He exaggerated a small problem to get Houston's attention.", "He was confused and did not know what had really happened.", "He was joking because he believed nothing serious was wrong."], why: "An oxygen tank had exploded and power was draining away, yet he only said they had 'had a problem.'" },
      { q: "How is most of the passage organized?", a: "as a series of problems and the solutions to them", wrong: ["as a comparison of two different spacecraft", "as a list of the astronauts' training steps", "as a description of the moon's surface"], why: "Each section presents a danger (lost power, cold, carbon dioxide) and how the crew or engineers dealt with it." },
      { q: "Lovell's phrase 'successful failure' most likely means that the mission...", a: "missed its goal but still brought the crew home alive.", wrong: ["reached the moon but lost the command module.", "worked only because the spare filters were round.", "failed because the engineers made a mistake."], why: "The crew 'abandoned any hope of a moon landing' (the failure), but all three returned safely to Earth (the success)." },
    ],
  },
  {
    id: 'r12', lv: 3, title: "The Tomato Thief",
    text: "Marisol's tomato plants were the finest on Cedar Street. She had raised them from seeds, watered them every morning before school, and occasionally talked to them, a habit her brother Luis considered deeply embarrassing. So when her ripest tomatoes began disappearing, Marisol took it personally.\n\n'It's obviously Mrs. Gruber,' Luis declared. Their elderly neighbor had once complained that the tall plants blocked her view of the street, and Luis considered that practically a confession.\n\nMarisol was tempted to agree, but she was reluctant to accuse anyone without proof. Instead, she designed a trap. It was not a cruel trap but a camera trap: she taped an old phone inside a plastic box, cut a hole for the lens, and connected it to a motion sensor from her robotics kit. Whenever something moved near the plants, the phone would capture a photograph.\n\nThe first night, the camera recorded forty-two pictures of the same moth, so Marisol lowered the sensor.\n\nThe second night, it recorded nothing at all, because the tape loosened and the box toppled over, so Marisol bought stronger tape.\n\nOn the third night, the system finally worked, and the next morning, Marisol scrolled through the images and gasped. There, illuminated by moonlight, stood a plump raccoon on its hind legs, gripping a red tomato in both paws as if it were a sandwich.\n\nMarisol thought about how close she had come to marching next door and making an accusation that she could never have taken back. That afternoon, she carried a bag of her best tomatoes to Mrs. Gruber's porch and knocked.\n\n'These are for you,' she said. 'I grew them myself.'\n\nMrs. Gruber looked startled, then pleased. The following week, she appeared at the door with a plate of cookies and a surprisingly useful tip about raccoon-proof fencing.\n\nMarisol installed the fence. She also adopted a new habit, one that proved more valuable than any of her inventions: gathering the facts before deciding what they meant.",
    qs: [
      { q: "As used in paragraph 3, what does 'reluctant' mean?", a: "unwilling or hesitant", wrong: ["excited or eager", "angry or upset", "certain or sure"], why: "Although she was 'tempted to agree,' she held back from accusing anyone 'without proof,' so she was unwilling to do it." },
      { q: "Why does Marisol most likely bring tomatoes to Mrs. Gruber?", a: "She feels guilty that she nearly blamed her unfairly.", wrong: ["She hopes Mrs. Gruber will pay for more of them.", "She still suspects Mrs. Gruber took the others.", "She wants Mrs. Gruber to help build the fence."], why: "Right before the visit, Marisol thinks about 'how close she had come' to making an accusation she 'could never have taken back.'" },
      { q: "Which sentence best states the theme of the story?", a: "It is wiser to gather evidence than to trust a hunch.", wrong: ["Neighbors who complain are usually guilty of something.", "Raccoons are the most destructive pests in any garden.", "A good invention almost always works on the first try."], why: "Luis trusts a hunch about Mrs. Gruber, but Marisol's evidence proves it wrong, and she ends by valuing 'gathering the facts before deciding what they meant.'" },
    ],
  },
  {
    id: 'r13', lv: 3, title: "The Miracle on Ice",
    text: "In February 1980, the Winter Olympics came to the small village of Lake Placid, New York. The United States men's hockey team was composed mostly of college players, and their average age was only about twenty-one. Few experts expected them to win any medal at all.\n\nThe Soviet Union's team was a different matter. Its players were seasoned veterans who trained together almost all year, and although they were officially amateurs, hockey was essentially their full-time job. The Soviets had captured the gold medal at four consecutive Olympics. Less than two weeks before the Games, they had overwhelmed the Americans 10 to 3 in an exhibition game at Madison Square Garden.\n\nThe American coach, Herb Brooks, understood that his players could not match the Soviets in experience. Instead, he concentrated on conditioning. For months he drove them through exhausting practices, determined that his team would be able to skate just as fast in the final minutes of a game as in the first.\n\nOn February 22, the two teams met. The Soviets took the lead three separate times, but each time the Americans responded with a goal of their own. Then, with exactly ten minutes remaining, team captain Mike Eruzione fired a shot past the Soviet goalie, giving the United States its first lead of the game, 4 to 3.\n\nFor the final ten minutes, the Americans blocked shot after shot as the Soviets attacked relentlessly. As the last seconds ticked away, broadcaster Al Michaels shouted, 'Do you believe in miracles? Yes!' The players flung their sticks into the air and piled on top of one another.\n\nMany people assume that this famous victory earned the gold medal, but it did not. Two days later, the Americans had to face Finland, and they trailed again entering the final period. Once more they rallied, winning 4 to 2. Only then was the gold theirs.",
    qs: [
      { q: "Why does the author mention the 10 to 3 exhibition game?", a: "to show how unlikely an American victory seemed", wrong: ["to explain how the Soviets lost the gold medal", "to describe the final game against Finland", "to suggest that Herb Brooks was a poor coach"], why: "The Soviets had 'overwhelmed' the Americans just before the Olympics, which shows how big an underdog the U.S. team was." },
      { q: "Which detail best suggests that Brooks's focus on conditioning paid off?", a: "The Americans held off the Soviets for the final ten minutes.", wrong: ["The Soviets had won four Olympic gold medals in a row.", "The American team was made up mostly of college players.", "Al Michaels shouted about miracles as the game ended."], why: "Brooks wanted a team that could skate hard 'in the final minutes,' and in the last ten minutes the Americans blocked 'shot after shot' to protect their lead." },
      { q: "As used in paragraph 2, what does 'seasoned' most nearly mean?", a: "experienced", wrong: ["flavored", "exhausted", "boastful"], why: "The Soviets are described as veterans who trained together almost all year, in contrast to the young American college players." },
    ],
  },
  {
    id: 'r14', lv: 3, title: "The Birthday Breakfast",
    text: "For their mother's birthday, the twins, Ezra and Ruby, resolved to make her breakfast in bed. They had a plan, and they had a recipe, but what they did not have, as it turned out, was the slightest idea what they were doing.\n\nEzra was responsible for the pancakes. The recipe called for one cup of flour, but because he could not locate the measuring cup, he substituted Dad's enormous coffee mug, which was approximately the size of a flowerpot. The resulting batter was so thick that the spoon remained standing upright in the bowl without any assistance.\n\nRuby was in charge of fresh orange juice. She sliced twelve oranges in half and squeezed them with her bare hands, and the juice traveled into the glass, across the counter, into her left eye, and somehow onto the ceiling. When she finally finished, she had produced approximately three sips.\n\nAt 7:15, the smoke alarm began shrieking. The first pancake had transformed into something resembling a hockey puck. Even the dog, a creature who regularly devoured socks, sniffed it suspiciously and walked away.\n\nAt 7:20, Mom appeared in the kitchen doorway in her bathrobe. Her gaze traveled slowly from the flour on the floor to the juice on the ceiling to the blackened disk smoking in the pan. Ezra and Ruby froze where they stood: Ezra was still clutching the spatula, and Ruby had a slice of orange tangled in her hair.\n\n'We were making you breakfast,' Ruby explained in a very small voice.\n\nFor a long moment, Mom said nothing at all. Then she sat down at the sticky table, took a sip of the three-sip orange juice, and declared that it was the finest she had ever tasted.\n\n'Next year,' she added, reaching for a napkin, 'maybe I could help?'\n\nThe pancakes were completely inedible. It was still, she insisted for years afterward, her favorite birthday breakfast ever.",
    qs: [
      { q: "Which sentence best states the theme of the story?", a: "The love behind a gift can matter more than how it turns out.", wrong: ["Cooking should only ever be done by adults in the family.", "Twins should never try to work together on a project.", "Following a recipe exactly always leads to good results."], why: "The pancakes were inedible, yet it was 'her favorite birthday breakfast ever,' because the twins were trying to do something kind." },
      { q: "Why does the author mention that the dog 'regularly devoured socks'?", a: "to stress how unappealing the pancake was", wrong: ["to show that the twins forgot to feed it", "to explain why the smoke alarm went off", "to show that the dog was hungry that day"], why: "A dog that eats socks will eat almost anything, so its refusal to eat the pancake shows how awful the pancake was." },
      { q: "What does Mom's question, 'maybe I could help?', most likely suggest?", a: "She appreciates the effort but hopes to prevent another mess.", wrong: ["She is angry and plans to cook by herself from now on.", "She thinks the twins should never be allowed to cook again.", "She wants to teach them how to squeeze orange juice only."], why: "She praises the juice and calls it her favorite breakfast, but she is 'reaching for a napkin' in a sticky kitchen, so she wants to guide them next time." },
    ],
  },
  {
    id: 'r15', lv: 3, title: "The Great Monarch Journey",
    text: "Every fall, millions of monarch butterflies in the eastern United States and Canada begin an extraordinary journey. They fly south, some as far as 3,000 miles, to spend the winter in the mountain forests of central Mexico. A monarch weighs less than a paper clip. Yet its migration is one of the longest of any insect on Earth.\n\nWhat makes the journey even more puzzling is that no single butterfly makes the whole round trip. Most monarchs live only two to six weeks. During spring and summer, several short-lived generations are born, and each one moves a little farther north. The monarchs that hatch in late summer, however, are different. Often called the super generation, they can live up to eight months. That is long enough to fly to Mexico, survive the winter, and start the trip back north in spring.\n\nConsequently, the butterflies that arrive in Mexico have never been there before. Neither their parents nor their grandparents ever saw those forests. Yet year after year, the monarchs find the same groves of fir trees high in the mountains, where the cool air lets them rest without burning up their energy. Researchers believe the butterflies steer by the position of the sun, combined with an inner clock that keeps track of the time of day. Some evidence suggests they may also sense Earth's magnetic field, almost like a built-in compass.\n\nIn Mexico, monarchs cluster in such huge numbers that branches sag beneath their weight. In recent decades, though, their numbers have dropped sharply. Monarch caterpillars can feed only on milkweed, and as milkweed disappears from farms and roadsides, the butterflies lose their food supply. Logging and changing weather also threaten their winter forests. In response, many families and schools have begun planting milkweed gardens. They hope that small, local efforts can help protect a journey that spans an entire continent.",
    qs: [
      { q: "Why does the author begin paragraph 3 with the word 'Consequently'?", a: "to show that the next idea results from the monarchs' short lives", wrong: ["to introduce a new topic about milkweed and caterpillars", "to show that scientists disagree about the super generation", "to compare monarchs with other insects that migrate"], why: "Because no single butterfly makes the whole round trip, the ones arriving in Mexico 'have never been there before.'" },
      { q: "What can the reader infer about how monarchs find their winter forests?", a: "They rely on built-in senses, not on memory or teaching.", wrong: ["They follow older butterflies that made the trip before.", "They remember the route from their previous winter.", "They are guided south each autumn by scientists."], why: "No monarch, parent, or grandparent has seen the forests, so they must rely on built-in tools like the sun, an inner clock, and possibly magnetism." },
      { q: "Which statement best expresses the central idea of the passage?", a: "The monarch migration is remarkable, but it now faces serious threats.", wrong: ["Monarch caterpillars are able to eat only one kind of plant.", "Monarchs live much longer than most other kinds of insects.", "Scientists have fully explained how monarchs find their way."], why: "Most of the passage describes the astonishing journey, and the last paragraph explains the population decline and its causes." },
    ],
  },

  // ---------- Level 4: grade 7, 340-420 words ----------
  {
    id: 'r16', lv: 4, title: "Endurance Found",
    text: "In 1914, the explorer Ernest Shackleton set out to do something no one had ever done: cross the entire continent of Antarctica on foot. His ship was called Endurance, a name inspired by his family motto, 'By endurance we conquer.' The name would prove remarkably appropriate, although not for the ship itself.\n\nIn January 1915, before the expedition could even reach land, Endurance became trapped in the frozen Weddell Sea. For months the ship drifted helplessly, locked in the pack ice, until the ice began to squeeze it. The wooden hull groaned, splintered, and finally collapsed. In November 1915, Endurance sank beneath the ice. Twenty-eight men were now stranded on drifting floes, hundreds of miles from anyone who could help.\n\nThey camped on the ice for months, surviving largely on seals and penguins, until the floes began breaking apart beneath them. The men then rowed three small lifeboats to Elephant Island, a barren, windswept rock so remote that no rescue ship would ever think to search there. Shackleton recognized that waiting meant almost certain death. He and five companions therefore sailed a small lifeboat, the James Caird, roughly 800 miles across some of the most violent ocean on the planet to South Georgia Island. They landed on the empty side of the island. From there, three of them hiked for about thirty-six hours across unmapped, glacier-covered mountains to reach a whaling station.\n\nIt took Shackleton four tries to force a rescue ship through the ice to Elephant Island. When he finally arrived in August 1916, the twenty-two men stranded there had been sheltering for more than four months beneath two overturned boats. Every member of the crew survived.\n\nFor more than a century, Endurance lay somewhere on the floor of the Weddell Sea. Then, in March 2022, an expedition using underwater robots located it nearly 10,000 feet below the surface. The images astonished the world. The ship was almost perfectly preserved, its wheel still upright and the word ENDURANCE clearly visible across the stern. Because the frigid Antarctic water contains no wood-eating worms, the wreck had scarcely decayed.\n\nThe discovery came exactly one hundred years to the day after Shackleton was buried on South Georgia.",
    qs: [
      { q: "Why does the author say the name was appropriate, 'although not for the ship itself'?", a: "The crew endured terrible hardship, but the ship was destroyed.", wrong: ["The ship lasted far longer than anyone had expected.", "The crew renamed the ship after it sank in the ice.", "The ship's name could still be read on its stern."], why: "Endurance was crushed and sank, while the men survived months on the ice, an 800-mile voyage, and a mountain crossing." },
      { q: "In paragraph 3, the word 'therefore' shows that the voyage of the James Caird was...", a: "a response to the danger of waiting on Elephant Island", wrong: ["a plan Shackleton made before leaving England", "an attempt to search for the sunken ship", "a shortcut to the far side of Antarctica"], why: "The sentence before says 'waiting meant almost certain death,' so 'therefore' introduces what Shackleton did because of that danger." },
      { q: "Which detail best explains why the wreck was so well preserved?", a: "The water contains no wood-eating worms.", wrong: ["Underwater robots photographed the ship.", "The ship's wheel was still standing upright.", "The ship had sunk in November of 1915."], why: "The text gives the cause directly: 'Because the frigid Antarctic water contains no wood-eating worms, the wreck had scarcely decayed.'" },
    ],
  },
  {
    id: 'r17', lv: 4, title: "The Light on Gull Point",
    text: "For seven consecutive nights, Caleb had observed it from his bedroom window: a light blinking across the bay from the abandoned lighthouse on Gull Point. The sequence never varied, consisting of three short flashes, three long ones, and three short ones, followed by a stretch of darkness before the pattern resumed.\n\nNo keeper had operated the lighthouse in twenty years, and its entrance was secured with a rusty chain, while according to local legend the spiral staircase inside had deteriorated long ago. Caleb's friend Jasmine was convinced that the light belonged to a ghost, while Caleb, who generally preferred explanations involving criminals, suspected smugglers signaling to a boat offshore. Whatever the truth turned out to be, he was determined to uncover it.\n\nHe recorded the sequence in a notebook and researched it online, where he learned that three short, three long, and three short flashes spelled SOS in Morse code, the international signal of distress.\n\nCaleb's stomach lurched as he wondered whether someone was trapped out there, injured and alone.\n\nHe sprinted downstairs to find his grandmother, who was sitting beside the kitchen window with a cup of tea, exactly as she did every evening. When he breathlessly described his discovery, however, she did not look alarmed. To his bewilderment, she looked guilty.\n\nWithout a word, she withdrew a small, heavy flashlight from the pocket of her cardigan, aimed it toward Gull Point, and clicked out the identical pattern, and a moment later, across the dark water, the lighthouse answered.\n\n'That's Walter,' she admitted. 'He was the last keeper, and he still lives in the cottage behind the lighthouse, so he has a key to that chain. When we were your age, we used to signal each other across the bay every night, and last week we decided to find out whether either of us still remembered the code.'\n\n'But why SOS?' Caleb demanded. 'That means help!'\n\nGrandma's mouth twitched as she replied, 'It was the only signal we both remembered.'\n\nCaleb studied the blinking light for a long moment, then turned back to his grandmother, whose cheeks had become unmistakably pink.\n\n'So,' he said slowly, 'is Walter your boyfriend?'\n\nGrandma aimed the flashlight directly at him and clicked it twice, which he was fairly certain meant 'Go to bed.'",
    qs: [
      { q: "Why does Grandma look guilty rather than alarmed?", a: "She knows she is partly responsible for the signals.", wrong: ["She forgot to lock the lighthouse door that night.", "She thinks Caleb should have been asleep by now.", "She believes a ghost really lives on Gull Point."], why: "Right after looking guilty, she pulls out a flashlight and sends the same pattern, and the lighthouse answers her." },
      { q: "As used in paragraph 5, what does 'bewilderment' mean?", a: "confusion", wrong: ["anger", "relief", "boredom"], why: "Caleb expects his grandmother to be alarmed by a distress signal, so her guilty look puzzles him." },
      { q: "Which detail best supports the idea that Grandma has romantic feelings for Walter?", a: "Her cheeks became unmistakably pink.", wrong: ["She drank tea by the window every evening.", "She kept a flashlight in her cardigan pocket.", "She explained that Walter was the last keeper."], why: "Her blushing comes just as Caleb thinks about Walter, and it leads directly to his question, 'is Walter your boyfriend?'" },
    ],
  },
  {
    id: 'r18', lv: 4, title: "The Mold That Changed Medicine",
    text: "In September 1928, the Scottish scientist Alexander Fleming came back from a family vacation to a cluttered lab. Before leaving, he had stacked up glass dishes in which he was growing bacteria, tiny germs that can cause serious infections. He had neglected to clean them.\n\nWhile sorting through the dishes, Fleming noticed something peculiar. A fuzzy mold had begun growing on one of them. Around the mold was a clear ring where the bacteria had died. Something made by the mold was evidently killing the germs.\n\nMany scientists might have thrown the spoiled dish away without a second glance. Fleming, instead, grew more of the mold, a type called Penicillium, which is related to the mold that grows on stale bread. He found that the juice it made could kill many kinds of harmful bacteria, and he named the substance penicillin.\n\nFleming, however, struggled to produce pure penicillin in large amounts. For about ten years, his discovery got little attention. Then, around 1940, a team at Oxford University led by Howard Florey and Ernst Chain revived his research. They found ways to purify penicillin and showed that it could cure infections, first in mice and then in people. Unlike earlier treatments, penicillin worked against many of the deadly bacteria that doctors had long been powerless to stop.\n\nThe timing proved crucial. World War II was raging, and countless soldiers were dying not from their wounds themselves but from the infections that followed. American companies learned to grow the mold in enormous tanks, and by 1944 there was enough penicillin to treat Allied troops on a large scale.\n\nIn 1945, Fleming, Florey, and Chain shared the Nobel Prize in Physiology or Medicine. Fleming later remarked, 'One sometimes finds what one is not looking for.'\n\nYet in his Nobel lecture, Fleming also issued a warning. If people took too little of the drug, he cautioned, bacteria could become resistant to it, meaning that the medicine would stop working against them. Today, antibiotic resistance is one of the most serious threats to world health, which is why doctors urge patients to use antibiotics only when they truly need them.",
    qs: [
      { q: "Which statement best expresses the central idea of the passage?", a: "An accidental discovery became a vital medicine that must be used wisely.", wrong: ["Fleming's messy habits slowed the progress of medicine for many years.", "World War II was the reason scientists first began to study mold.", "Florey and Chain discovered penicillin while working at Oxford University."], why: "The passage traces penicillin from a mold on an uncleaned dish to a life-saving drug, then ends with Fleming's warning about resistance." },
      { q: "Why does the author include the detail that Fleming 'had neglected to clean' his dishes?", a: "to show that the discovery depended partly on chance", wrong: ["to criticize Fleming for running a careless lab", "to explain why penicillin was so hard to purify", "to show that Fleming disliked doing his own work"], why: "The mold grew only because the dishes were left out, which fits Fleming's own remark that 'one sometimes finds what one is not looking for.'" },
      { q: "How does the final paragraph change the focus of the passage?", a: "It shifts from penicillin's success to a warning about its limits.", wrong: ["It shifts from Fleming's life to the history of World War II.", "It shifts from the lab in England to factories in America.", "It shifts from bacteria to the mold that grows on bread."], why: "After describing the Nobel Prize, the last paragraph begins 'Yet' and explains that bacteria can become resistant to antibiotics." },
    ],
  },
  {
    id: 'r19', lv: 4, title: "Follow the Water",
    text: "According to the trail guide, the hike to Eagle Lake should have taken four hours, yet five hours after setting out, Maddie and her younger brother, Sam, stood on a rocky ridge, staring down at a lake that was definitely not Eagle Lake.\n\n'We missed a turn,' Maddie admitted, though she suspected that Sam had already figured that out.\n\nSam, who was nine and had been complaining about his feet since lunch, collapsed onto a boulder and announced that he was not walking another step.\n\nMaddie checked her phone and found no signal, and meanwhile the sun was already sinking toward the western peaks and the wind carried a sudden chill. She felt panic rising in her chest, the same tight, fluttering sensation she experienced before important tests, but she forced herself to breathe slowly, reminding herself that panicking would accomplish nothing, whereas thinking clearly might accomplish a great deal.\n\nFrom the bottom of her backpack, she pulled out the paper map that her father had insisted she pack, the one she had rolled her eyes at that morning. After a minute of careful study, she located the ridge where they stood and the lake below them, and then she noticed something she had previously overlooked: a thin blue line representing a stream that flowed out of the lake and wound down the valley until it crossed the very trail on which they had started.\n\n'Water always runs downhill,' she murmured, mostly to herself. 'If we follow the stream, it should lead us back to the trail.'\n\nSam remained skeptical, insisting that it was just a guess.\n\n'It's a map,' Maddie replied, 'and a map is better than a guess.'\n\nThe descent was anything but easy. The stream twisted through dense brush, and twice they were forced to clamber over fallen logs. Sam grumbled continuously, which Maddie eventually decided was reassuring, since a silent Sam would have worried her far more.\n\nJust as the light faded to orange, they heard voices, and minutes later the stream passed beneath a small wooden footbridge, where a park ranger holding a radio was standing beside their father.\n\nHe hugged them both so tightly that Sam squeaked, and then he glanced at the creased map in Maddie's hand.\n\n'You used it,' he said, trying not to look too pleased.\n\n'Don't let it go to your head,' Maddie said. But she kept the map.",
    qs: [
      { q: "Why does the author mention that Maddie had rolled her eyes at the map that morning?", a: "to create irony, since the item she dismissed ends up saving them", wrong: ["to show that Maddie usually forgets to pack important things", "to explain why Maddie did not know how to read the map", "to show that Sam was the one who had packed the map"], why: "Rolling her eyes shows she thought the map was pointless, yet the stream on that map leads them back to safety." },
      { q: "Why does Maddie decide that Sam's grumbling is 'reassuring'?", a: "It shows he still has his usual energy and spirit.", wrong: ["It shows that he finally agrees with her plan.", "It shows that they are very close to the trail.", "It shows that he is too tired to keep walking."], why: "The text explains that 'a silent Sam would have worried her far more,' so his complaining means he is still himself." },
      { q: "What does the final sentence, 'But she kept the map,' suggest?", a: "Maddie values the map more than she is willing to admit.", wrong: ["Maddie plans to return the map to the park ranger.", "Maddie is still angry at her father for the long hike.", "Maddie thinks the map led them in the wrong direction."], why: "She teases her father not to 'let it go to his head,' yet she holds on to the map, showing she appreciates it." },
    ],
  },
  {
    id: 'r20', lv: 4, title: "The Great Molasses Flood",
    text: "January 15, 1919, was an unusually mild winter day in Boston, Massachusetts. In the crowded North End neighborhood, residents were eating lunch, children were playing in the streets, and workers were unloading freight near the harbor. Looming over Commercial Street stood a huge steel tank, fifty feet tall and ninety feet wide. It held more than two million gallons of molasses, a thick syrup made from sugar cane.\n\nShortly after noon, people nearby heard a rapid series of pops like machine-gun fire as the steel rivets holding the tank together burst loose. Seconds later, the entire structure split open.\n\nA wave of molasses, roughly twenty-five feet high at its peak, surged through the streets at about thirty-five miles per hour. It knocked buildings off their foundations and buckled the steel supports of an elevated railway. People and horses were swept up and trapped in the syrup, which grew even thicker as the evening air turned colder. Because molasses is so thick, victims could barely move, and rescuers struggled to reach them. Twenty-one people died, and about 150 were hurt.\n\nAt first, the company that owned the tank insisted that anarchists had blown it up on purpose with a bomb. After years of hearings, however, a court-appointed investigator concluded that the company itself was responsible. The tank had been constructed hastily and cheaply, and it had never been properly tested. Neighbors testified that it had leaked from the very start. The leaks were so bad that local families collected the dripping molasses for their kitchens. The company's response was to paint the tank brown.\n\nThe cleanup required weeks of labor. Firefighters hosed down the streets with salt water pumped from the harbor, and the harbor itself remained stained brown for months. Some longtime residents claimed that on hot summer afternoons, the neighborhood smelled faintly sweet for decades afterward.\n\nThe disaster produced one significant reform. In the years that followed, Massachusetts and later other states began to require that trained engineers check and approve the plans for large building projects. It was a tragic way for such rules to begin, and Boston has never entirely forgotten it.",
    qs: [
      { q: "What can the reader infer from the company's claim that anarchists bombed the tank?", a: "The company was trying to shift the blame away from itself.", wrong: ["The company had proof that the tank was attacked that day.", "The company wanted the police to protect its other tanks.", "The company believed the molasses itself was explosive."], why: "The investigator later found 'the company itself was responsible' for a tank that was built hastily, never tested, and leaking." },
      { q: "Which detail best supports the idea that the company knew the tank had problems?", a: "It painted the tank brown after the leaks appeared.", wrong: ["The tank was fifty feet tall and ninety feet wide.", "The wave moved at about thirty-five miles per hour.", "The harbor remained stained brown for months."], why: "Neighbors said the tank leaked from the beginning and that 'the company's response was to paint the tank brown,' which hid the leaks instead of fixing them." },
      { q: "As used in paragraph 4, what does 'hastily' mean?", a: "too quickly and without enough care", wrong: ["slowly and with great attention", "secretly and against the law", "proudly and in front of crowds"], why: "The tank was built 'hastily and cheaply' and 'never properly tested,' which points to rushed, careless work." },
    ],
  },

  // ---------- Level 5: grade 8, 380-460 words ----------
  {
    id: 'r21', lv: 5, title: "The Fake in the Dutch Room",
    text: "Our seventh-grade trip to the Hartwell Art Museum promised to be thoroughly uneventful until, halfway through the bus ride, our art teacher, Mr. Okafor, stood up and made an announcement that transformed the entire day. Somewhere in the museum's Dutch gallery, he informed us, the curators had concealed a fake, and whoever identified it and could prove the claim would win lunch at the museum cafe. Thirty students sat up simultaneously.\n\nThe Dutch gallery was devoted to paintings from the 1600s: shadowy kitchens, ships battling storms, and solemn merchants in black coats with stiff white collars. Most of my classmates rushed toward the largest and most celebrated canvas, a portrait of a merchant holding a letter, and scrutinized it as though it might eventually confess.\n\nI am no expert on art, but I have always been drawn to details, so my partner, Lena, and I proceeded methodically from one painting to the next. We examined shoes, pewter dishes, candle flames, and the delicate network of cracks that forms as old paint ages. Everything appeared precisely as ancient as it was supposed to be.\n\nWith five minutes remaining, Lena collapsed onto a bench and suggested, mostly out of frustration, that perhaps there was no fake at all and the challenge itself was the trick.\n\nHer remark lodged in my mind, because I suddenly realized that Mr. Okafor had never actually claimed that a painting was fake. He had said that something in the gallery was. I surveyed the room again with fresh eyes: frames, spotlights, a bench, and beside every painting, a small white card identifying its title, its artist, and the year it was completed.\n\nI hurried back along the wall, comparing each card with the painting beside it, because many Dutch artists had signed their work in a corner, occasionally adding the date. Beside a modest picture titled Still Life with Lemons, the card read 1641. In the painting's darkened corner, however, in tiny, meticulous letters, the artist had written 1614, and I raised my hand so abruptly that my shoulder popped.\n\nMr. Okafor examined the card, then the corner of the canvas, and smiled. The painting was entirely authentic, he explained; the museum had simply reversed two digits on the label. Every year, he added, students spent the entire hour interrogating the paintings, and hardly anyone bothered to read the labels.\n\nLena and I shared the prize. I argued that this was only fair, since her complaint had inspired my idea, whereas she argued that it was only fair because she was starving. We were both correct.",
    qs: [
      { q: "Which sentence best states the theme of the story?", a: "Solving a problem sometimes requires questioning your own assumptions.", wrong: ["The most famous painting in a room is usually the one that is fake.", "Museums should not play tricks on students who come to visit them.", "Working alone is the most reliable way to win any competition."], why: "Everyone assumed the fake was a painting. The narrator wins only after realizing the teacher said 'something in the gallery,' not a painting." },
      { q: "What role does Lena's remark play in the plot?", a: "It accidentally leads the narrator to rethink the teacher's exact words.", wrong: ["It convinces the narrator to give up and sit down on the bench.", "It points the narrator directly to the painting of the lemons.", "It reveals that Lena had already secretly solved the mystery."], why: "Lena says it out of frustration, but it 'lodged' in the narrator's mind and prompted the realization that Mr. Okafor never said a painting was fake." },
      { q: "As used in the story, what does 'meticulous' most nearly mean?", a: "extremely careful and precise", wrong: ["faded and difficult to read", "hurried and somewhat messy", "large and easy to notice"], why: "The letters are 'tiny' and painted into a corner with care, which fits the meaning of precise, careful work." },
    ],
  },
  {
    id: 'r22', lv: 5, title: "The Code That Was Never Broken",
    text: "During World War II, the United States Marines fighting in the Pacific confronted a serious obstacle. Japanese code breakers were highly skilled at listening in on American radio messages and figuring them out. As a result, battle plans could be exposed within hours. The Marines needed a way to communicate that was fast, accurate, and, ideally, impossible for the enemy to crack.\n\nThe solution emerged from the Navajo Nation. Navajo is a highly complex language whose sounds, tones, and grammar differ sharply from those of English or Japanese. In the early 1940s, it was spoken almost only on Navajo land in the Southwest. It had no widely used written form, and very few outsiders could understand it. The idea of using it was proposed by Philip Johnston, an engineer who had grown up on the Navajo reservation as the son of a missionary.\n\nIn 1942, the Marines recruited twenty-nine young Navajo men to build a code based on their language. The code had two components. First, the men chose Navajo words for military terms that had no Navajo equivalent: a submarine became 'iron fish,' a fighter plane became 'hummingbird,' and a bomb became 'egg.' Second, they created an alphabet in which each English letter was matched with one or more Navajo words, so that unfamiliar names could be spelled out. Consequently, even a fluent Navajo speaker who had not been trained in the code would have heard only a bewildering string of unrelated words.\n\nBecause written copies could be captured, the code talkers memorized the entire system. In tests, they could encode, send, and decode a three-line message in about twenty seconds. The coding machines of the time usually needed about thirty minutes for the same task.\n\nIn all, about 400 Navajo men served as code talkers, taking part in every major Marine assault in the Pacific from 1942 to 1945. During the first two days at Iwo Jima, six code talkers worked around the clock and sent more than 800 messages without a single error. A signal officer later declared that without the Navajos, the Marines would never have taken the island. The Japanese never broke the code.\n\nIronically, the very secrecy that made the code successful also delayed recognition of the men who created it. The program remained classified until 1968, and the code talkers were forbidden to discuss their service. Not until 2001 did the original twenty-nine receive the Congressional Gold Medal, by which time only a handful were still alive.",
    qs: [
      { q: "Why would a Navajo speaker who had NOT been trained in the code have been unable to understand the messages?", a: "The words stood for military terms and letters, not their usual meanings.", wrong: ["The messages were spoken in Japanese rather than in Navajo.", "The code talkers spoke far too quickly for anyone to follow.", "The messages used a written alphabet that only Marines could read."], why: "Words like 'iron fish' meant submarine, and other words stood for English letters, so an untrained speaker 'would have heard only a bewildering string of unrelated words.'" },
      { q: "Why does the author describe the delay in honoring the code talkers as ironic?", a: "The secrecy that protected the code also hid the men's achievement.", wrong: ["The code talkers did not want any medals for their service.", "The Japanese learned about the code before the Americans did.", "The government honored the code talkers before the war ended."], why: "The last paragraph says 'the very secrecy that made the code successful also delayed recognition,' since the program stayed classified until 1968." },
      { q: "Which statement best describes the author's main purpose?", a: "to explain how the Navajo code worked and why its creators deserve recognition", wrong: ["to argue that machines are always slower than people at sending messages", "to describe the battle of Iwo Jima from the Japanese point of view", "to teach readers how to speak and write the Navajo language"], why: "The passage explains the language, the two-part code, and its success, then ends by noting how long the men waited to be honored." },
    ],
  },
  {
    id: 'r23', lv: 5, title: "A Message in a Bottle for the Stars",
    text: "In 1977, NASA launched two spacecraft, Voyager 1 and Voyager 2, on an ambitious tour of the outer solar system. Their main job was scientific: to photograph and measure Jupiter and Saturn and, in the case of Voyager 2, Uranus and Neptune as well. Yet each spacecraft also carried an unusual passenger, a message meant for anyone who might someday find it.\n\nThe message took the form of a phonograph record, twelve inches across, made of copper and coated with gold. A committee led by the astronomer Carl Sagan had only a few months to decide what it should contain. The members faced a deeply difficult question: if thinking beings from another world found this object, what should they learn about Earth?\n\nIn the end, the committee chose natural sounds, such as wind, rain, thunder, birdsong, and whales, along with human ones, such as footsteps, laughter, a heartbeat, and a mother with her baby. They recorded spoken greetings in fifty-five languages, from ancient Sumerian to modern Mandarin. They stored 115 images on the record, showing everything from the structure of DNA to a crowded supermarket. Finally, they added about ninety minutes of music from many cultures, from Bach and Beethoven to a Navajo night chant and Chuck Berry's 'Johnny B. Goode.'\n\nBecause an alien finder would have no idea how to play a record, the designers engraved the cover with diagrams that explain how to play it and how fast to spin it. Another diagram shows where our sun is by comparing its position with fourteen pulsars. These are collapsed stars that flash with steady, distinctive rhythms, so they could, in theory, serve as landmarks in space.\n\nRealistically, the chance that anyone will ever find the records is minuscule. Space is so vast that it is almost impossible to imagine. Although the Voyagers move at tens of thousands of miles per hour, they are practically crawling compared with the distances between stars. Voyager 1 crossed into interstellar space in 2012, the first human-made object to do so. Even so, it will not pass even fairly close to another star for about 40,000 years.\n\nSagan understood these odds perfectly well. He compared the record to a bottle tossed into the cosmic ocean and remarked that launching it said something very hopeful about life on this planet. Perhaps, then, the record's most important audience was never really an alien civilization. By forcing people to decide what showed humanity at its best, the project revealed what they valued most.",
    qs: [
      { q: "As used in paragraph 5, what does 'minuscule' mean?", a: "extremely small", wrong: ["fairly likely", "easy to measure", "growing quickly"], why: "The author explains that space is 'so vast that it is almost impossible to imagine' and that Voyager 1 will not near another star for 40,000 years, so the chance is extremely small." },
      { q: "Which detail best shows that the designers thought carefully about the needs of a non-human finder?", a: "They engraved diagrams explaining how to play the record.", wrong: ["They chose greetings in fifty-five human languages.", "They plated the copper record with a layer of gold.", "They included the rock song 'Johnny B. Goode.'"], why: "The text says the diagrams were added 'because an alien finder would have no idea how to play a record.'" },
      { q: "What does the author suggest in the final paragraph?", a: "The record may matter more for what it revealed about people than for being found.", wrong: ["The record will most likely be found by aliens within the next few centuries.", "Sagan regretted the project once he understood how vast space really is.", "The committee should have included more science and less music and art."], why: "The author says the 'most important audience was never really an alien civilization' and that the project 'revealed what they valued most.'" },
    ],
  },
  {
    id: 'r24', lv: 5, title: "The Homework Machine",
    text: "By the middle of seventh grade, Theo Park had produced eleven inventions. Nine of them had exploded, a ratio that Theo considered thoroughly respectable for an inventor of his age and budget. The tenth, a self-buttering toaster, had been permanently banned by his mother following an unfortunate incident involving the kitchen curtains. The eleventh, however, was the invention that transformed everything: HOMER, the Homework Machine.\n\nHOMER consisted of a laptop program, a secondhand printer, and a mechanical arm that Theo had assembled from a desk lamp. A user typed in an assignment, and HOMER produced the answers in handwriting that was almost indistinguishable from Theo's own. On its first night of operation, it completed his math homework in four minutes, and Theo spent the remainder of the evening playing video games, feeling like the most brilliant person who had ever lived.\n\nFor two weeks, his existence was flawless. His homework was invariably complete and remarkably neat, his grades improved steadily, and his teachers began writing encouraging comments in the margins of his papers. Then Ms. Delgado announced a surprise quiz.\n\nThe problems on the quiz were precisely the kind that HOMER had been solving every night. Theo stared at the first question with mounting horror. He was certain he had seen one exactly like it, and he could even picture the lamp arm writing out the solution, but he had absolutely no idea how HOMER had arrived there.\n\nHe received a 54, and at the top of the page, in red ink, Ms. Delgado had written two words: 'Let's talk.'\n\nThat evening, Theo sat at his desk and regarded HOMER for a long time, recognizing that the machine was ingenious and undeniably efficient but had also taught him precisely nothing.\n\nHe briefly considered deleting the program entirely, but instead he devoted the following three nights to rewriting it. When he finished, HOMER no longer supplied any answers at all. Whenever Theo became stuck, it asked him questions instead, such as what he already knew, what the problem was actually asking, and what he could attempt first. The new version was slower and considerably more irritating, and it was, Theo grudgingly admitted, rather like having Ms. Delgado installed in his bedroom.\n\nOn the next quiz, he earned a 91. He never told anyone about HOMER, but he did modify the title on its start screen, which no longer read HOMEWORK MACHINE. It now read THINKING MACHINE, a name that was considerably more accurate and slightly less fun.",
    qs: [
      { q: "Which sentence best states the theme of the story?", a: "Shortcuts that do the work for you can keep you from truly learning.", wrong: ["Inventions are only worth building if they are fun to use.", "Teachers should stop giving their students surprise quizzes.", "Machines will always solve problems better than students can."], why: "HOMER made Theo's homework perfect, but it 'taught him precisely nothing,' and he failed the quiz." },
      { q: "Why does the author include the detail that Theo 'could even picture the lamp arm writing out the solution'?", a: "to show that watching an answer is not the same as understanding it", wrong: ["to show that the lamp arm was the best part of Theo's invention", "to explain that Theo had memorized every answer HOMER wrote", "to suggest that HOMER had secretly broken down before the quiz"], why: "Theo remembers seeing the answer written, yet he 'had absolutely no idea how HOMER had arrived there.'" },
      { q: "What does the author suggest by calling the new name 'more accurate and slightly less fun'?", a: "The program now makes Theo do the hard thinking himself.", wrong: ["The program now writes with much neater handwriting.", "The program now plays video games with Theo at night.", "The program now finishes his math homework even faster."], why: "The rewritten HOMER asks questions instead of giving answers, so it truly helps him think, which is useful but takes more effort." },
    ],
  },
  {
    id: 'r25', lv: 5, title: "Not So Birdbrained",
    text: "For generations, people have used the word 'birdbrain' as an insult, suggesting that birds are simply not very smart. Researchers who study crows and their relatives, however, increasingly suspect that the insult deserves to be retired.\n\nCrows belong to a family of birds known as corvids, which also includes ravens, jays, and magpies. For their body size, corvids have unusually large brains. Those brains are packed with neurons, the cells that process information. In some problem-solving tests, corvids do as well as young children. Some species can hide thousands of seeds in the fall and find many of them again months later.\n\nOne of the most famous experiments involved a New Caledonian crow named Betty at Oxford University in 2002. Researchers gave her an upright tube with a small bucket of food at the bottom, along with a straight piece of wire. Unable to reach the bucket with the straight wire, Betty bent it into a hook, lowered it into the tube, and lifted the bucket out. No one had ever shown her how to do this.\n\nCrows also remember individual human faces with remarkable precision. At the University of Washington, a team led by the biologist John Marzluff wore a certain rubber mask while they caught and banded wild crows. The birds were then released unharmed. For years afterward, whenever anyone walked across campus wearing that mask, crows gathered to scold and dive at the wearer, including many birds that had never been captured. The crows had apparently communicated the 'dangerous' face to one another, while a volunteer wearing a different mask was largely ignored.\n\nIn Japan, some crows have been observed dropping walnuts onto busy roads so that passing cars will crack the shells. Then they wait for a red light to stop the traffic before hopping out to collect the pieces.\n\nNone of this evidence means that crows think exactly as humans do, since their brains are organized very differently from ours. What the research does suggest is that complex intelligence can evolve separately in very different kinds of animals, not only in mammals with large brains. Scientists are still trying to learn exactly how bird brains manage such feats. In the meantime, the next time a crow appears to be watching you, it may really be doing exactly that, and it may remember you long after you have forgotten it.",
    qs: [
      { q: "What is the author's main purpose?", a: "to challenge the common belief that birds are unintelligent", wrong: ["to explain how scientists train crows to use simple tools", "to argue that crows think in exactly the same way as people", "to describe the history and origin of the word 'birdbrain'"], why: "The passage opens by saying the insult 'deserves to be retired' and then offers example after example of crow intelligence." },
      { q: "What can the reader infer from the mask experiment?", a: "Crows can share information about threats with other crows.", wrong: ["Crows are frightened by every kind of human mask.", "Crows attack anyone who walks across the campus.", "Crows forget human faces after a few short weeks."], why: "Birds 'that had never been captured' also scolded the mask, so the crows 'had apparently communicated' the danger to one another." },
      { q: "Why does the author include the sentence that begins 'None of this evidence means'?", a: "to keep readers from claiming more than the research shows", wrong: ["to prove that crows are actually less intelligent than people", "to argue that the experiments described were badly designed", "to introduce a new example of crows solving a problem"], why: "After many impressive examples, the author adds a limit: crows do not think 'exactly as humans do,' because their brains are organized differently." },
    ],
  },
];
