// Spelling: commonly misspelled words, US grade 5-8. def = short definition shown as the clue. American spelling.
export const SPELLING = [
  // ===== Level 1 (grades 4-5) =====
  { en: 'because', def: 'for the reason that', lv: 1 },
  { en: 'friend', def: 'a person you like and trust', lv: 1 },
  { en: 'beautiful', def: 'very pretty or lovely to look at', lv: 1 },
  { en: 'believe', def: 'to accept that something is true', lv: 1 },
  { en: 'different', def: 'not the same as something else', lv: 1 },
  { en: 'library', def: 'a building where you can borrow books', lv: 1 },
  { en: 'probably', def: 'very likely to happen or be true', lv: 1 },
  { en: 'surprise', def: 'something that happens that you did not expect', lv: 1 },
  { en: 'tomorrow', def: 'the day after today', lv: 1 },
  { en: 'minute', def: 'a unit of time equal to sixty seconds', lv: 1 },
  { en: 'answer', def: 'a reply to a question', lv: 1 },
  { en: 'island', def: 'a piece of land with water all around it', lv: 1 },
  { en: 'piece', def: 'one part of something, like a slice of cake', lv: 1 },
  { en: 'neighbor', def: 'a person who lives next door to you', lv: 1 },
  { en: 'enough', def: 'as much as you need', lv: 1 },
  { en: 'through', def: 'in one side and out the other', lv: 1 },
  { en: 'laugh', def: 'the sound you make when something is funny', lv: 1 },
  { en: 'guess', def: 'to give an answer without being sure', lv: 1 },
  { en: 'guard', def: 'a person whose job is to protect a place', lv: 1 },
  { en: 'special', def: 'better or more important than usual', lv: 1 },
  { en: 'finally', def: 'at last, after a long wait', lv: 1 },
  { en: 'beginning', def: 'the start of something', lv: 1 },
  { en: 'address', def: 'the street and number where someone lives', lv: 1 },
  { en: 'cousin', def: 'the child of your aunt or uncle', lv: 1 },
  { en: 'caught', def: 'past tense of catch', lv: 1 },
  { en: 'daughter', def: 'a parent\'s female child', lv: 1 },
  { en: 'height', def: 'how tall someone or something is', lv: 1 },
  { en: 'weird', def: 'very strange or unusual', lv: 1 },
  { en: 'eighth', def: 'coming right after seventh', lv: 1 },
  { en: 'science', def: 'the study of nature through experiments', lv: 1 },
  { en: 'scissors', def: 'a cutting tool with two blades', lv: 1 },
  { en: 'castle', def: 'a large stone fortress where kings lived', lv: 1 },
  { en: 'listen', def: 'to pay attention so you can hear', lv: 1 },
  { en: 'climb', def: 'to go up using your hands and feet', lv: 1 },
  { en: 'thumb', def: 'the short, thick finger on the side of your hand', lv: 1 },
  { en: 'autumn', def: 'the season between summer and winter', lv: 1 },
  { en: 'chocolate', def: 'a sweet brown treat made from cocoa', lv: 1 },
  { en: 'vegetable', def: 'a plant you eat, like carrots or peas', lv: 1 },
  { en: 'straight', def: 'without any bend or curve', lv: 1 },
  { en: 'whistle', def: 'a high sound made by blowing through your lips', lv: 1 },
  { en: 'breakfast', def: 'the first meal of the day', lv: 1 },
  { en: 'quiet', def: 'making very little noise', lv: 1 },
  { en: 'stomach', def: 'the body part where swallowed food goes', lv: 1 },
  { en: 'machine', def: 'a device with moving parts that does work', lv: 1 },
  { en: 'ceiling', def: 'the inside top surface of a room', lv: 1 },
  { en: 'field', def: 'an open area of land, often covered in grass', lv: 1 },
  { en: 'busy', def: 'having a lot of things to do', lv: 1 },
  { en: 'knife', def: 'a tool with a sharp blade for cutting food', lv: 1 },
  { en: 'wrestle', def: 'to fight by grabbing and pinning someone down', lv: 1 },
  { en: 'juice', def: 'the liquid squeezed out of fruit', lv: 1 },

  // ===== Level 2 (grades 5-6) =====
  { en: 'separate', def: 'to pull apart or keep apart', lv: 2 },
  { en: 'receive', def: 'to get something that someone gives or sends you', lv: 2 },
  { en: 'knowledge', def: 'everything you know and have learned', lv: 2 },
  { en: 'business', def: 'a company that sells goods or services', lv: 2 },
  { en: 'tongue', def: 'the muscle in your mouth used for tasting', lv: 2 },
  { en: 'calendar', def: 'a chart that shows the days, weeks, and months', lv: 2 },
  { en: 'government', def: 'the group of people who run a country', lv: 2 },
  { en: 'interesting', def: 'grabbing and holding your attention', lv: 2 },
  { en: 'favorite', def: 'the one you like best', lv: 2 },
  { en: 'license', def: 'an official card that lets you drive', lv: 2 },
  { en: 'grammar', def: 'the rules for how words go together', lv: 2 },
  { en: 'humorous', def: 'funny and making people laugh', lv: 2 },
  { en: 'nuisance', def: 'a person or thing that annoys you', lv: 2 },
  { en: 'disappear', def: 'to vanish from sight', lv: 2 },
  { en: 'disappoint', def: 'to let someone down by failing their hopes', lv: 2 },
  { en: 'truly', def: 'honestly and sincerely', lv: 2 },
  { en: 'argument', def: 'a disagreement with raised voices', lv: 2 },
  { en: 'ninety', def: 'the number that is nine times ten', lv: 2 },
  { en: 'forty', def: 'the number that is four times ten', lv: 2 },
  { en: 'village', def: 'a very small town in the countryside', lv: 2 },
  { en: 'lightning', def: 'a bright flash of electricity during a storm', lv: 2 },
  { en: 'already', def: 'before now or before a certain time', lv: 2 },
  { en: 'character', def: 'a person or creature in a story', lv: 2 },
  { en: 'cemetery', def: 'a place where the dead are buried', lv: 2 },
  { en: 'mischief', def: 'playful behavior that causes small trouble', lv: 2 },
  { en: 'foreign', def: 'from or about another country', lv: 2 },
  { en: 'sincerely', def: 'in a heartfelt and honest way', lv: 2 },
  { en: 'temperature', def: 'how hot or cold something is', lv: 2 },
  { en: 'experience', def: 'something that you have lived through', lv: 2 },
  { en: 'excellent', def: 'extremely good; of the highest quality', lv: 2 },
  { en: 'exercise', def: 'physical activity that keeps your body fit', lv: 2 },
  { en: 'restaurant', def: 'a place where you pay to eat a meal', lv: 2 },
  { en: 'schedule', def: 'a plan that lists times for events', lv: 2 },
  { en: 'awkward', def: 'clumsy or uncomfortable', lv: 2 },
  { en: 'bicycle', def: 'a two-wheeled vehicle that you pedal', lv: 2 },
  { en: 'squirrel', def: 'a bushy-tailed rodent that gathers nuts', lv: 2 },
  { en: 'pajamas', def: 'loose clothes you wear to bed', lv: 2 },
  { en: 'muscle', def: 'body tissue that tightens to move your bones', lv: 2 },
  { en: 'doubt', def: 'a feeling of not being sure', lv: 2 },
  { en: 'column', def: 'a tall stone pillar holding up a roof', lv: 2 },
  { en: 'achieve', def: 'to succeed in reaching a goal', lv: 2 },
  { en: 'fierce', def: 'wild, strong, and ready to attack', lv: 2 },
  { en: 'niece', def: 'the daughter of your brother or sister', lv: 2 },
  { en: 'ancient', def: 'from a time very long ago', lv: 2 },
  { en: 'quarter', def: 'one of four equal parts', lv: 2 },
  { en: 'journey', def: 'a long trip from one place to another', lv: 2 },
  { en: 'caterpillar', def: 'a wormlike larva that turns into a butterfly', lv: 2 },
  { en: 'especially', def: 'more than usual; above all', lv: 2 },
  { en: 'across', def: 'from one side to the other', lv: 2 },
  { en: 'balloon', def: 'a rubber bag that you fill with air', lv: 2 },

  // ===== Level 3 (grade 6) =====
  { en: 'necessary', def: 'needed; something you must have', lv: 3 },
  { en: 'rhythm', def: 'a regular, repeated pattern of sounds or beats', lv: 3 },
  { en: 'conscience', def: 'the inner voice that tells right from wrong', lv: 3 },
  { en: 'occasionally', def: 'once in a while; not often', lv: 3 },
  { en: 'embarrass', def: 'to make someone feel awkward and ashamed', lv: 3 },
  { en: 'definitely', def: 'without any doubt; for sure', lv: 3 },
  { en: 'occurrence', def: 'something that happens; an event', lv: 3 },
  { en: 'recommend', def: 'to suggest something as good or worth trying', lv: 3 },
  { en: 'privilege', def: 'a special right or advantage', lv: 3 },
  { en: 'independent', def: 'free and not controlled by others', lv: 3 },
  { en: 'guarantee', def: 'a firm promise that something will happen', lv: 3 },
  { en: 'apparent', def: 'easy to see or understand; obvious', lv: 3 },
  { en: 'committee', def: 'a group chosen to make decisions together', lv: 3 },
  { en: 'conscious', def: 'awake and aware of what is around you', lv: 3 },
  { en: 'discipline', def: 'training that teaches self-control and obeying rules', lv: 3 },
  { en: 'environment', def: 'the natural world of land, air, and water', lv: 3 },
  { en: 'exaggerate', def: 'to make something sound bigger than it really is', lv: 3 },
  { en: 'existence', def: 'the state of being real or alive', lv: 3 },
  { en: 'familiar', def: 'well known to you from before', lv: 3 },
  { en: 'fascinate', def: 'to hold someone\'s attention completely', lv: 3 },
  { en: 'harass', def: 'to keep bothering or pestering someone', lv: 3 },
  { en: 'hygiene', def: 'keeping yourself clean to stay healthy', lv: 3 },
  { en: 'immediately', def: 'right away, with no delay', lv: 3 },
  { en: 'interrupt', def: 'to break in while someone is talking', lv: 3 },
  { en: 'jewelry', def: 'rings, necklaces, and bracelets', lv: 3 },
  { en: 'leisure', def: 'free time when you can relax', lv: 3 },
  { en: 'maneuver', def: 'a skillful move or steering action', lv: 3 },
  { en: 'miniature', def: 'a very small copy of something', lv: 3 },
  { en: 'misspell', def: 'to write a word with the wrong letters', lv: 3 },
  { en: 'noticeable', def: 'easy to see or notice', lv: 3 },
  { en: 'parallel', def: 'lines that run side by side and never meet', lv: 3 },
  { en: 'persistent', def: 'refusing to give up; continuing firmly', lv: 3 },
  { en: 'possession', def: 'something that you own', lv: 3 },
  { en: 'preferred', def: 'liked better than the other choices', lv: 3 },
  { en: 'succeed', def: 'to do what you set out to do', lv: 3 },
  { en: 'thorough', def: 'careful and complete, leaving nothing out', lv: 3 },
  { en: 'twelfth', def: 'coming right after eleventh', lv: 3 },
  { en: 'vacuum', def: 'a machine that sucks up dirt from floors', lv: 3 },
  { en: 'villain', def: 'the bad guy in a story', lv: 3 },
  { en: 'acquire', def: 'to get or gain something', lv: 3 },
  { en: 'appearance', def: 'the way someone or something looks', lv: 3 },
  { en: 'bizarre', def: 'extremely strange and odd', lv: 3 },
  { en: 'criticize', def: 'to point out what is wrong with something', lv: 3 },
  { en: 'deceive', def: 'to trick someone into believing a lie', lv: 3 },
  { en: 'dilemma', def: 'a hard choice between two options', lv: 3 },
  { en: 'disastrous', def: 'causing great damage or total failure', lv: 3 },
  { en: 'grateful', def: 'feeling thankful for something', lv: 3 },
  { en: 'medieval', def: 'from the Middle Ages, the time of knights', lv: 3 },
  { en: 'receipt', def: 'a slip of paper proving you paid', lv: 3 },
  { en: 'siege', def: 'surrounding a city or castle to force surrender', lv: 3 },

  // ===== Level 4 (grade 7) =====
  { en: 'accommodate', def: 'to have enough room for; to provide lodging', lv: 4 },
  { en: 'millennium', def: 'a period of one thousand years', lv: 4 },
  { en: 'maintenance', def: 'the work of keeping something in good repair', lv: 4 },
  { en: 'acquaintance', def: 'a person you know slightly, but not well', lv: 4 },
  { en: 'aggressive', def: 'ready to attack or fight', lv: 4 },
  { en: 'amateur', def: 'someone who does an activity for fun, not pay', lv: 4 },
  { en: 'camouflage', def: 'colors or patterns that help something hide', lv: 4 },
  { en: 'catastrophe', def: 'a sudden, terrible disaster', lv: 4 },
  { en: 'commitment', def: 'a promise to stick with something', lv: 4 },
  { en: 'consensus', def: 'general agreement among everyone in a group', lv: 4 },
  { en: 'curiosity', def: 'a strong wish to know or learn', lv: 4 },
  { en: 'desperate', def: 'willing to try anything because things are hopeless', lv: 4 },
  { en: 'exhilarate', def: 'to make someone feel thrilled and full of energy', lv: 4 },
  { en: 'fluorescent', def: 'glowing with very bright, vivid color', lv: 4 },
  { en: 'gauge', def: 'a dial or meter that measures something', lv: 4 },
  { en: 'guidance', def: 'help and advice from someone who knows more', lv: 4 },
  { en: 'hierarchy', def: 'a system of ranks from highest to lowest', lv: 4 },
  { en: 'hypocrisy', def: 'saying one thing but doing the opposite', lv: 4 },
  { en: 'indispensable', def: 'absolutely necessary; impossible to do without', lv: 4 },
  { en: 'irresistible', def: 'too tempting to say no to', lv: 4 },
  { en: 'knowledgeable', def: 'knowing a lot about a subject', lv: 4 },
  { en: 'manageable', def: 'possible to handle or control', lv: 4 },
  { en: 'memento', def: 'a small object kept to remember something', lv: 4 },
  { en: 'minuscule', def: 'so tiny it is hard to see', lv: 4 },
  { en: 'omission', def: 'something left out or skipped', lv: 4 },
  { en: 'opportunity', def: 'a good chance to do something', lv: 4 },
  { en: 'pamphlet', def: 'a thin booklet with information', lv: 4 },
  { en: 'pastime', def: 'a hobby or activity done for fun', lv: 4 },
  { en: 'perseverance', def: 'continuing to try even when it is hard', lv: 4 },
  { en: 'playwright', def: 'a person who writes plays for the stage', lv: 4 },
  { en: 'precede', def: 'to come before something in time or order', lv: 4 },
  { en: 'prejudice', def: 'an unfair opinion formed without knowing the facts', lv: 4 },
  { en: 'pronunciation', def: 'the way a word is said out loud', lv: 4 },
  { en: 'psychology', def: 'the science of the mind and behavior', lv: 4 },
  { en: 'rehearsal', def: 'a practice run before a performance', lv: 4 },
  { en: 'sergeant', def: 'an army or police officer above corporal', lv: 4 },
  { en: 'silhouette', def: 'a dark outline seen against a light background', lv: 4 },
  { en: 'sophomore', def: 'a student in the second year of high school', lv: 4 },
  { en: 'souvenir', def: 'something you buy to remember a trip', lv: 4 },
  { en: 'surveillance', def: 'close watching of a person or place', lv: 4 },
  { en: 'symmetry', def: 'exactly matching halves on both sides', lv: 4 },
  { en: 'temperamental', def: 'moody and quick to get upset', lv: 4 },
  { en: 'unanimous', def: 'agreed on by every single person', lv: 4 },
  { en: 'vengeance', def: 'punishment given in return for a wrong; revenge', lv: 4 },
  { en: 'yacht', def: 'a large, fancy boat used for pleasure', lv: 4 },
  { en: 'cantaloupe', def: 'a melon with orange flesh and a rough rind', lv: 4 },
  { en: 'quarantine', def: 'keeping sick people apart so disease will not spread', lv: 4 },
  { en: 'accidentally', def: 'by mistake; without meaning to', lv: 4 },
  { en: 'convenience', def: 'being easy and handy to use', lv: 4 },
  { en: 'exhaust', def: 'to tire out completely', lv: 4 },

  // ===== Level 5 (grades 7-8) =====
  { en: 'onomatopoeia', def: 'a word that imitates a sound, like buzz or boom', lv: 5 },
  { en: 'conscientious', def: 'careful and hardworking about doing things right', lv: 5 },
  { en: 'mischievous', def: 'liking to cause playful trouble', lv: 5 },
  { en: 'pharaoh', def: 'a king of ancient Egypt', lv: 5 },
  { en: 'liaison', def: 'a person who connects two groups and passes messages', lv: 5 },
  { en: 'bureaucracy', def: 'a government system full of officials and paperwork', lv: 5 },
  { en: 'colonel', def: 'a high-ranking military officer below a general', lv: 5 },
  { en: 'connoisseur', def: 'an expert judge of fine things like food or art', lv: 5 },
  { en: 'entrepreneur', def: 'a person who starts and runs a new business', lv: 5 },
  { en: 'hemorrhage', def: 'heavy, dangerous bleeding', lv: 5 },
  { en: 'idiosyncrasy', def: 'an odd habit that is unique to one person', lv: 5 },
  { en: 'lieutenant', def: 'a junior military officer below a captain', lv: 5 },
  { en: 'questionnaire', def: 'a written list of questions for a survey', lv: 5 },
  { en: 'restaurateur', def: 'a person who owns and runs an eating place', lv: 5 },
  { en: 'sacrilegious', def: 'disrespectful toward something holy', lv: 5 },
  { en: 'supersede', def: 'to replace something older or less important', lv: 5 },
  { en: 'acquiesce', def: 'to agree quietly without arguing', lv: 5 },
  { en: 'chauffeur', def: 'a person paid to drive someone around', lv: 5 },
  { en: 'dachshund', def: 'a small dog with a long body and short legs', lv: 5 },
  { en: 'ecstasy', def: 'a feeling of overwhelming joy', lv: 5 },
  { en: 'fuchsia', def: 'a bright purplish pink color', lv: 5 },
  { en: 'guerrilla', def: 'a fighter in a small, independent armed band', lv: 5 },
  { en: 'handkerchief', def: 'a small square of cloth for wiping your nose', lv: 5 },
  { en: 'kaleidoscope', def: 'a tube with mirrors showing changing colorful patterns', lv: 5 },
  { en: 'labyrinth', def: 'a complicated maze that is hard to escape', lv: 5 },
  { en: 'laryngitis', def: 'a swollen voice box that makes you lose your voice', lv: 5 },
  { en: 'mnemonic', def: 'a trick or rhyme that helps you remember', lv: 5 },
  { en: 'paraphernalia', def: 'all the gear and equipment for an activity', lv: 5 },
  { en: 'parliament', def: 'the lawmaking assembly in countries like Britain', lv: 5 },
  { en: 'pneumonia', def: 'a serious infection of the lungs', lv: 5 },
  { en: 'rendezvous', def: 'a planned meeting at a set time and place', lv: 5 },
  { en: 'reminiscent', def: 'reminding you of something from the past', lv: 5 },
  { en: 'rhinoceros', def: 'a huge African or Asian animal with a horned snout', lv: 5 },
  { en: 'surreptitious', def: 'done secretly so nobody notices', lv: 5 },
  { en: 'threshold', def: 'the strip of floor at a doorway', lv: 5 },
  { en: 'vicious', def: 'cruel and violent', lv: 5 },
  { en: 'zucchini', def: 'a long green summer squash', lv: 5 },
  { en: 'psychiatrist', def: 'a doctor who treats mental illness', lv: 5 },
  { en: 'rhetoric', def: 'the art of persuasive speaking or writing', lv: 5 },
  { en: 'sapphire', def: 'a precious blue gemstone', lv: 5 },
  { en: 'anonymous', def: 'with a name that is unknown or kept secret', lv: 5 },
  { en: 'asthma', def: 'a condition that makes breathing difficult', lv: 5 },
  { en: 'camaraderie', def: 'friendship and trust among teammates', lv: 5 },
  { en: 'caffeine', def: 'the substance in coffee that keeps you awake', lv: 5 },
  { en: 'deterrent', def: 'something that discourages people from acting', lv: 5 },
  { en: 'jeopardy', def: 'danger of loss or harm', lv: 5 },
  { en: 'liquefy', def: 'to turn a solid or gas into liquid', lv: 5 },
  { en: 'mayonnaise', def: 'a creamy white sauce made from eggs and oil', lv: 5 },
  { en: 'resuscitate', def: 'to bring someone back to consciousness or life', lv: 5 },
  { en: 'sovereign', def: 'a king or queen who rules a nation', lv: 5 },
];
