// Vocabulary bank, US grade 6. lv 1 = grade 5, 3 = on grade 6, 5 = grades 7-8 stretch. def = short kid-friendly definition.
export const WORDS = [
  // ---------- Level 1 (grade 5) ----------
  { en: "abundant", def: "more than enough of something", lv: 1, pos: "adj", ex: "Blueberries were so abundant at camp that we ate them with every meal." },
  { en: "cautious", def: "careful to avoid danger or mistakes", lv: 1, pos: "adj", ex: "Be cautious on the icy trail, or you will slide right into the creek." },
  { en: "gloomy", def: "dark and sad, without hope", lv: 1, pos: "adj", ex: "The sky stayed gray and gloomy all weekend, so our soccer game got canceled." },
  { en: "eager", def: "excited and wanting to do something soon", lv: 1, pos: "adj", ex: "Leo was eager to try the new skate park the moment it opened." },
  { en: "fragile", def: "easily broken or damaged", lv: 1, pos: "adj", ex: "Pack the model rocket carefully, because the fins are fragile." },
  { en: "fierce", def: "powerful and intense, like a wild animal", lv: 1, pos: "adj", ex: "The fierce goalie dove at every shot and blocked them all." },
  { en: "timid", def: "shy and easily frightened", lv: 1, pos: "adj", ex: "The timid kitten hid under the couch whenever the doorbell rang." },
  { en: "sturdy", def: "strong and solidly built", lv: 1, pos: "adj", ex: "We built a sturdy tree house that held all five of us." },
  { en: "vast", def: "extremely large in area", lv: 1, pos: "adj", ex: "From the plane we saw a vast desert stretching as far as we could see." },
  { en: "rare", def: "not found or seen very often", lv: 1, pos: "adj", ex: "My brother traded his rare golden card for three ordinary ones." },
  { en: "loyal", def: "always faithful to your friends or team", lv: 1, pos: "adj", ex: "Our dog is so loyal that he waits by the door until we come home." },
  { en: "clumsy", def: "moving awkwardly and often dropping things", lv: 1, pos: "adj", ex: "I was so clumsy at the bowling alley that I dropped the ball on my foot." },
  { en: "curious", def: "wanting to learn or know more", lv: 1, pos: "adj", ex: "The curious scientist opened the strange box to see what was inside." },
  { en: "weary", def: "very tired after a lot of effort", lv: 1, pos: "adj", ex: "After the ten-mile hike, the weary scouts fell asleep right away." },
  { en: "swift", def: "moving very fast", lv: 1, pos: "adj", ex: "The swift runner stole second base before the catcher could throw." },
  { en: "humble", def: "not proud and not showing off", lv: 1, pos: "adj", ex: "Even after scoring three goals, Sam stayed humble and thanked his teammates." },
  { en: "ancient", def: "extremely old, from long ago", lv: 1, pos: "adj", ex: "We found ancient coins near the ruins of a Roman fort." },
  { en: "cozy", def: "warm, comfortable and snug", lv: 1, pos: "adj", ex: "The cabin was cozy, with a crackling fire and thick blankets." },
  { en: "frantic", def: "wild with worry or hurry", lv: 1, pos: "adj", ex: "Dad made a frantic search for the car keys when we were already late." },
  { en: "hollow", def: "having an empty space inside", lv: 1, pos: "adj", ex: "The raccoon was sleeping inside a hollow log in the woods." },
  { en: "damp", def: "a little bit wet", lv: 1, pos: "adj", ex: "My socks were still damp from the rain when I put on my cleats." },
  { en: "shallow", def: "not deep from top to bottom", lv: 1, pos: "adj", ex: "The little kids splashed around in the shallow end of the pool." },
  { en: "tense", def: "stiff and nervous, unable to relax", lv: 1, pos: "adj", ex: "The last minute of the tied game was so tense that nobody in the stands sat down." },
  { en: "grateful", def: "thankful for something someone did", lv: 1, pos: "adj", ex: "I was grateful when my sister helped me finish my science poster." },
  { en: "stubborn", def: "refusing to change your mind", lv: 1, pos: "adj", ex: "My stubborn little brother would not eat broccoli, even for dessert." },
  { en: "fortunate", def: "having good luck", lv: 1, pos: "adj", ex: "We were fortunate that the storm passed before the big game started." },
  { en: "visible", def: "able to be seen", lv: 1, pos: "adj", ex: "On a clear night, the space station is visible from our backyard." },
  { en: "drenched", def: "completely soaking wet", lv: 1, pos: "adj", ex: "We got drenched in the water balloon fight and loved every second." },
  { en: "hesitate", def: "pause before acting because you are unsure", lv: 1, pos: "verb", ex: "Don't hesitate to shoot when you have an open lane to the goal." },
  { en: "gather", def: "pick up and collect things from different places", lv: 1, pos: "verb", ex: "Please gather all the puzzle pieces before the dog eats one." },
  { en: "wander", def: "walk around with no plan", lv: 1, pos: "verb", ex: "We like to wander through the museum and stop wherever looks cool." },
  { en: "vanish", def: "disappear suddenly from sight", lv: 1, pos: "verb", ex: "The magician made the coin vanish right in front of my eyes." },
  { en: "scold", def: "speak angrily to someone who did wrong", lv: 1, pos: "verb", ex: "Mom will scold us if we track mud across the kitchen again." },
  { en: "grasp", def: "hold something tightly", lv: 1, pos: "verb", ex: "You must grasp the rope with both hands before you swing across the creek." },
  { en: "stumble", def: "trip and almost fall", lv: 1, pos: "verb", ex: "Watch out for tree roots so you don't stumble in the dark." },
  { en: "observe", def: "watch carefully to learn something", lv: 1, pos: "verb", ex: "We will observe the tadpoles every day and record how they change." },
  { en: "predict", def: "say what will happen before it does", lv: 1, pos: "verb", ex: "Can you predict which team will win the World Series this year?" },
  { en: "recover", def: "get better after being sick or hurt", lv: 1, pos: "verb", ex: "It took three weeks for my sprained ankle to recover." },
  { en: "collapse", def: "cave in or fall apart suddenly", lv: 1, pos: "verb", ex: "The sand castle began to collapse when the big wave hit it." },
  { en: "shiver", def: "shake because you are cold or scared", lv: 1, pos: "verb", ex: "We started to shiver after jumping into the freezing lake." },
  { en: "soar", def: "fly high in the air", lv: 1, pos: "verb", ex: "We watched the eagle soar above the cliffs without flapping once." },
  { en: "plunge", def: "dive or fall quickly downward", lv: 1, pos: "verb", ex: "The roller coaster will plunge straight down from the top of the hill." },
  { en: "conceal", def: "hide something so others cannot find it", lv: 1, pos: "verb", ex: "We tried to conceal the surprise gift under a pile of laundry." },
  { en: "devour", def: "eat something quickly and hungrily", lv: 1, pos: "verb", ex: "After practice, my brothers devour an entire pizza in five minutes." },
  { en: "scramble", def: "climb or crawl quickly using hands and feet", lv: 1, pos: "verb", ex: "We had to scramble up the rocks to reach the top of the hill." },
  { en: "boast", def: "talk proudly about yourself", lv: 1, pos: "verb", ex: "Jake likes to boast about his high score, but nobody has seen it." },
  { en: "glance", def: "look at something very quickly", lv: 1, pos: "verb", ex: "Always glance at the scoreboard before you take the final shot." },
  { en: "admire", def: "look up to with respect and liking", lv: 1, pos: "verb", ex: "I admire how my coach stays calm even when we are losing." },
  { en: "assemble", def: "put the parts of something together", lv: 1, pos: "verb", ex: "It took us two hours to assemble the new bunk beds." },
  { en: "rescue", def: "save someone from danger", lv: 1, pos: "verb", ex: "Firefighters climbed the ladder to rescue the cat from the roof." },
  { en: "purchase", def: "get something by paying money for it", lv: 1, pos: "verb", ex: "I saved my allowance for months to purchase a new video game." },
  { en: "require", def: "need something in order to work", lv: 1, pos: "verb", ex: "Most science experiments require goggles and careful measuring." },
  { en: "outcome", def: "the final result of something", lv: 1, pos: "noun", ex: "Nobody could guess the outcome of the game until the very last play." },
  { en: "journey", def: "a long trip from one place to another", lv: 1, pos: "noun", ex: "The journey to Grandma's house takes six hours by car." },
  { en: "rumor", def: "a story passed around that may be untrue", lv: 1, pos: "noun", ex: "A rumor spread that school would be closed, but it turned out to be false." },
  { en: "shelter", def: "a place that protects you from weather", lv: 1, pos: "noun", ex: "We built a shelter out of branches when the rain started." },
  { en: "burden", def: "a heavy load you have to carry", lv: 1, pos: "noun", ex: "Carrying everyone's backpacks was a real burden for our tired coach." },
  { en: "harvest", def: "the time when farmers pick their crops", lv: 1, pos: "noun", ex: "The farm needs extra helpers during the pumpkin harvest each October." },
  { en: "opponent", def: "a person or team you play against", lv: 1, pos: "noun", ex: "Our opponent in the final was the tallest team in the league." },
  { en: "habitat", def: "the natural home of an animal or plant", lv: 1, pos: "noun", ex: "The polar bear's habitat is shrinking as the Arctic ice melts." },
  { en: "fossil", def: "remains of a long dead creature in rock", lv: 1, pos: "noun", ex: "We found a fossil of a tiny fish inside a flat gray rock." },
  { en: "volunteer", def: "someone who helps without being paid", lv: 1, pos: "noun", ex: "My dad was a volunteer coach for our Little League team." },
  { en: "triumph", def: "a great victory or success", lv: 1, pos: "noun", ex: "Beating the champions was the biggest triumph in our school's history." },
  { en: "destination", def: "the place you are traveling to", lv: 1, pos: "noun", ex: "Our final destination was a water park with ten giant slides." },
  { en: "horizon", def: "the line where the sky meets land or sea", lv: 1, pos: "noun", ex: "We watched the sun sink below the horizon at the end of the day." },
  { en: "ancestor", def: "a family member who lived long ago", lv: 1, pos: "noun", ex: "My ancestor sailed from Ireland to New York more than a century ago." },
  { en: "avalanche", def: "a mass of snow sliding down a mountain", lv: 1, pos: "noun", ex: "The skiers stayed off the steep slope because of the avalanche warning." },
  { en: "blizzard", def: "a heavy snowstorm with strong winds", lv: 1, pos: "noun", ex: "The blizzard dumped two feet of snow, and school was closed for three days." },
  { en: "canyon", def: "a deep valley with steep rocky sides", lv: 1, pos: "noun", ex: "We could hear our echo bounce off the walls of the canyon." },
  { en: "mischief", def: "playful behavior that causes small trouble", lv: 1, pos: "noun", ex: "My twin brothers are always up to mischief when Mom is on the phone." },
  { en: "chore", def: "a regular job you do at home", lv: 1, pos: "noun", ex: "My least favorite chore is taking out the trash on Sunday night." },
  { en: "feast", def: "a large, special meal", lv: 1, pos: "noun", ex: "After the tournament, both teams shared a huge feast of tacos." },
  { en: "swarm", def: "a large group of insects moving together", lv: 1, pos: "noun", ex: "A swarm of bees chased us all the way across the field." },
  { en: "gadget", def: "a small, clever tool or device", lv: 1, pos: "noun", ex: "My uncle has a gadget that can open any jar in two seconds." },
  { en: "predator", def: "an animal that hunts others for food", lv: 1, pos: "noun", ex: "The hawk is a predator that can spot a mouse from high above." },
  { en: "invention", def: "a new device or idea someone came up with", lv: 1, pos: "noun", ex: "The light bulb was an invention that changed the whole world." },
  { en: "eventually", def: "in the end, after some time", lv: 1, pos: "adv", ex: "We got lost twice, but eventually we found the campsite." },
  { en: "gradually", def: "slowly, a little at a time", lv: 1, pos: "adv", ex: "The ice cream gradually melted as we walked home in the sun." },
  { en: "instantly", def: "right away, with no delay", lv: 1, pos: "adv", ex: "The lights went out and the noisy gym went silent instantly." },
  { en: "frequently", def: "happening many times", lv: 1, pos: "adv", ex: "Our cat frequently sleeps on my keyboard while I do homework." },

  // ---------- Level 2 ----------
  { en: "peculiar", def: "strange or unusual", lv: 2, pos: "adj", ex: "There was a peculiar smell coming from my brother's gym bag." },
  { en: "reliable", def: "able to be trusted to work or help", lv: 2, pos: "adj", ex: "Our old car is not fast, but it is reliable and never breaks down." },
  { en: "generous", def: "happy to give or share with others", lv: 2, pos: "adj", ex: "It was generous of Max to share his snacks with the whole bus." },
  { en: "anxious", def: "worried about what might happen", lv: 2, pos: "adj", ex: "I felt anxious the night before my first piano recital." },
  { en: "absurd", def: "silly in a way that makes no sense", lv: 2, pos: "adj", ex: "The idea of a penguin playing basketball is completely absurd." },
  { en: "adequate", def: "good enough for what is needed", lv: 2, pos: "adj", ex: "One water bottle is not adequate for an all-day hike in July." },
  { en: "hostile", def: "unfriendly and ready to fight", lv: 2, pos: "adj", ex: "The hostile crowd booed every time our team touched the ball." },
  { en: "keen", def: "very sharp, especially your senses", lv: 2, pos: "adj", ex: "Owls have keen eyesight that lets them hunt in the dark." },
  { en: "nimble", def: "quick and light on your feet", lv: 2, pos: "adj", ex: "The nimble squirrel leaped from branch to branch without slipping." },
  { en: "rigid", def: "stiff and unable to bend", lv: 2, pos: "adj", ex: "The cast kept my arm rigid so the bone could heal." },
  { en: "sincere", def: "honest and truly meaning what you say", lv: 2, pos: "adj", ex: "Her apology was sincere, so I forgave her right away." },
  { en: "tedious", def: "long, slow and boring", lv: 2, pos: "adj", ex: "Copying the whole dictionary page was a tedious punishment." },
  { en: "vacant", def: "not being used or lived in", lv: 2, pos: "adj", ex: "We played kickball in the vacant lot behind the grocery store." },
  { en: "vital", def: "absolutely necessary to live or work", lv: 2, pos: "adj", ex: "Water is vital for every living thing on Earth." },
  { en: "drowsy", def: "sleepy and half awake", lv: 2, pos: "adj", ex: "The warm classroom made everyone drowsy after lunch." },
  { en: "dense", def: "packed closely together", lv: 2, pos: "adj", ex: "The jungle was so dense that we could barely push through the vines." },
  { en: "feeble", def: "very weak and without strength", lv: 2, pos: "adj", ex: "The baby bird made a feeble chirp from the bottom of the nest." },
  { en: "jagged", def: "having sharp, uneven points", lv: 2, pos: "adj", ex: "Be careful of the jagged rocks at the bottom of the waterfall." },
  { en: "murky", def: "dark and dirty, hard to see through", lv: 2, pos: "adj", ex: "We couldn't see a single fish in the murky pond water." },
  { en: "obvious", def: "very easy to notice or understand", lv: 2, pos: "adj", ex: "It was obvious who ate the cookies, because Ben had crumbs all over his shirt." },
  { en: "competent", def: "having enough skill to do something well", lv: 2, pos: "adj", ex: "After a month of lessons, I became a competent swimmer." },
  { en: "defiant", def: "boldly refusing to obey", lv: 2, pos: "adj", ex: "The defiant puppy sat down and refused to walk another step." },
  { en: "legendary", def: "famous and talked about for years", lv: 2, pos: "adj", ex: "Michael Jordan is a legendary player who won six championships." },
  { en: "persistent", def: "continuing to try even when it is hard", lv: 2, pos: "adj", ex: "The persistent woodpecker kept knocking until it made a hole." },
  { en: "rugged", def: "rough and rocky, hard to cross", lv: 2, pos: "adj", ex: "The rugged mountain trail was only for experienced hikers." },
  { en: "solitary", def: "living or being alone", lv: 2, pos: "adj", ex: "The solitary wolf hunted far away from the rest of the pack." },
  { en: "urgent", def: "needing to be dealt with immediately", lv: 2, pos: "adj", ex: "The coach got an urgent call and had to leave practice early." },
  { en: "vague", def: "not clear or detailed", lv: 2, pos: "adj", ex: "His directions were so vague that we drove around the block four times." },
  { en: "linger", def: "stay somewhere longer than needed", lv: 2, pos: "verb", ex: "Fans like to linger outside the stadium hoping to get autographs." },
  { en: "rummage", def: "search messily through a pile of things", lv: 2, pos: "verb", ex: "I had to rummage through my closet to find my other cleat." },
  { en: "demolish", def: "tear down a building completely", lv: 2, pos: "verb", ex: "The crew will demolish the old gym and build a new one." },
  { en: "abandon", def: "leave behind and never return", lv: 2, pos: "verb", ex: "The sailors had to abandon the sinking ship and climb into lifeboats." },
  { en: "persuade", def: "get someone to agree by giving good reasons", lv: 2, pos: "verb", ex: "I tried to persuade my parents to let me stay up for the game." },
  { en: "accumulate", def: "slowly build up over time", lv: 2, pos: "verb", ex: "Dust began to accumulate on my old video game console in the attic." },
  { en: "astonish", def: "surprise someone very much", lv: 2, pos: "verb", ex: "The diver's triple flip will astonish the judges." },
  { en: "cease", def: "come to a stop", lv: 2, pos: "verb", ex: "The fireworks will cease at exactly ten o'clock, so watch closely." },
  { en: "clarify", def: "make something easier to understand", lv: 2, pos: "verb", ex: "Can you clarify the rules before we start the game?" },
  { en: "contribute", def: "give something to help a group", lv: 2, pos: "verb", ex: "Everyone will contribute five dollars for the class pizza party." },
  { en: "deceive", def: "trick someone into believing something false", lv: 2, pos: "verb", ex: "The fake punt was meant to deceive the other team." },
  { en: "decline", def: "politely say no to something", lv: 2, pos: "verb", ex: "I had to decline the party invitation because I had a game." },
  { en: "distract", def: "pull someone's attention away", lv: 2, pos: "verb", ex: "Don't distract the pitcher while he is trying to concentrate." },
  { en: "endure", def: "put up with something hard for a long time", lv: 2, pos: "verb", ex: "The explorers had to endure freezing winds for weeks." },
  { en: "exaggerate", def: "make something sound bigger than it is", lv: 2, pos: "verb", ex: "My uncle likes to exaggerate the size of every fish he catches." },
  { en: "flourish", def: "grow strongly and do very well", lv: 2, pos: "verb", ex: "Tomatoes flourish in our garden because they get lots of sun." },
  { en: "imitate", def: "copy the way someone acts or talks", lv: 2, pos: "verb", ex: "My little sister likes to imitate everything I say, which drives me crazy." },
  { en: "investigate", def: "search for facts to find out what happened", lv: 2, pos: "verb", ex: "The principal came to investigate who broke the trophy case." },
  { en: "migrate", def: "move to another region when seasons change", lv: 2, pos: "verb", ex: "Monarch butterflies migrate thousands of miles to Mexico every fall." },
  { en: "obstruct", def: "block the way", lv: 2, pos: "verb", ex: "A fallen tree can obstruct the trail for weeks after a storm." },
  { en: "preserve", def: "keep something safe from harm or decay", lv: 2, pos: "verb", ex: "Museums preserve old dinosaur bones so future kids can see them." },
  { en: "prohibit", def: "officially forbid something", lv: 2, pos: "verb", ex: "The pool rules prohibit running on the slippery deck." },
  { en: "retreat", def: "move back away from danger", lv: 2, pos: "verb", ex: "The knights had to retreat behind the castle walls when the dragon appeared." },
  { en: "revise", def: "reread your writing and fix it to make it better", lv: 2, pos: "verb", ex: "I had to revise my essay three times before it was ready." },
  { en: "hazard", def: "something that could cause danger", lv: 2, pos: "noun", ex: "The broken glass on the court was a hazard, so we stopped playing." },
  { en: "debris", def: "scattered pieces left after something breaks", lv: 2, pos: "noun", ex: "After the tornado, debris covered every street in town." },
  { en: "expedition", def: "an organized trip to explore a place", lv: 2, pos: "noun", ex: "The expedition spent a month mapping caves under the jungle." },
  { en: "ambition", def: "a strong wish to achieve something", lv: 2, pos: "noun", ex: "My ambition is to play in the NBA or design video games." },
  { en: "apprentice", def: "someone learning a trade from an expert", lv: 2, pos: "noun", ex: "The young apprentice spent years learning to make swords from the blacksmith." },
  { en: "colony", def: "a group of animals living together", lv: 2, pos: "noun", ex: "A colony of ants carried crumbs back to their underground nest." },
  { en: "companion", def: "someone you spend time or travel with", lv: 2, pos: "noun", ex: "My dog was my faithful companion on every bike ride." },
  { en: "descendant", def: "a later family member, like a grandchild or great-grandchild", lv: 2, pos: "noun", ex: "He claims he is a descendant of a famous pirate captain." },
  { en: "drought", def: "a long time without rain", lv: 2, pos: "noun", ex: "During the drought, the lake shrank and the grass turned brown." },
  { en: "fragment", def: "a small piece broken off something", lv: 2, pos: "noun", ex: "We found a fragment of a meteorite in the desert." },
  { en: "instinct", def: "an automatic urge to act without thinking", lv: 2, pos: "noun", ex: "Baby turtles follow their instinct and crawl straight toward the ocean." },
  { en: "landmark", def: "a famous place that is easy to recognize", lv: 2, pos: "noun", ex: "The Statue of Liberty is the most famous landmark in New York." },
  { en: "nuisance", def: "something or someone that is annoying", lv: 2, pos: "noun", ex: "The buzzing mosquito was a nuisance all night long." },
  { en: "obstacle", def: "something that stands in your way", lv: 2, pos: "noun", ex: "The final obstacle in the race was a giant mud pit." },
  { en: "quarrel", def: "an angry argument", lv: 2, pos: "noun", ex: "My brother and I had a quarrel over who got the front seat." },
  { en: "ritual", def: "an action repeated the same way every time", lv: 2, pos: "noun", ex: "Tapping the plate three times is my pregame ritual." },
  { en: "scheme", def: "a secret, sneaky plan", lv: 2, pos: "noun", ex: "The twins came up with a scheme to get out of doing the dishes." },
  { en: "specimen", def: "a sample collected for study", lv: 2, pos: "noun", ex: "We put the bug specimen in a jar to study under the microscope." },
  { en: "strategy", def: "a careful plan for winning", lv: 2, pos: "noun", ex: "Our strategy was to pass the ball quickly and tire out their defense." },
  { en: "summit", def: "the highest point of a mountain", lv: 2, pos: "noun", ex: "We took a picture at the summit with clouds below us." },
  { en: "glacier", def: "a huge, slow river of ice", lv: 2, pos: "noun", ex: "The glacier moves only a few feet each day down the valley." },
  { en: "gesture", def: "a hand movement that shows meaning", lv: 2, pos: "noun", ex: "The umpire made a gesture with his arm to signal the batter was out." },
  { en: "pedestrian", def: "a person walking along a road", lv: 2, pos: "noun", ex: "Drivers must stop when a pedestrian is in the crosswalk." },
  { en: "ally", def: "someone who joins your side to help", lv: 2, pos: "noun", ex: "In the game, my brother became my ally against the dragon." },
  { en: "abruptly", def: "suddenly and without warning", lv: 2, pos: "adv", ex: "The music stopped abruptly, and everyone froze in place." },
  { en: "deliberately", def: "done on purpose, not by accident", lv: 2, pos: "adv", ex: "He deliberately kicked the ball out of bounds to stop the clock." },
  { en: "briskly", def: "quickly and with energy", lv: 2, pos: "adv", ex: "We walked briskly to stay warm on the frozen sidewalk." },
  { en: "thoroughly", def: "completely, missing nothing", lv: 2, pos: "adv", ex: "Wash your hands thoroughly after handling the class snake." },

  // ---------- Level 3 (on grade 6) ----------
  { en: "ambiguous", def: "having more than one possible meaning", lv: 3, pos: "adj", ex: "The riddle was ambiguous, so both of our answers could be right." },
  { en: "futile", def: "having no chance of success", lv: 3, pos: "adj", ex: "Trying to outrun a cheetah on foot would be futile." },
  { en: "vivid", def: "very bright, clear and full of life", lv: 3, pos: "adj", ex: "I had a vivid dream that I was flying over the city." },
  { en: "reluctant", def: "not wanting to do something", lv: 3, pos: "adj", ex: "I was reluctant to jump off the high dive, but I finally did it." },
  { en: "obsolete", def: "out of date and no longer used", lv: 3, pos: "adj", ex: "Floppy disks are obsolete, so my dad's old computer is useless now." },
  { en: "notorious", def: "famous for something bad", lv: 3, pos: "adj", ex: "Our cat is notorious for knocking cups off the table." },
  { en: "elaborate", def: "detailed and with many parts", lv: 3, pos: "adj", ex: "We built an elaborate domino course that wound through three rooms." },
  { en: "authentic", def: "real and genuine, not fake", lv: 3, pos: "adj", ex: "The museum proved the dinosaur tooth was authentic." },
  { en: "candid", def: "saying exactly what you think, openly", lv: 3, pos: "adj", ex: "Coach gave a candid answer: we played badly and needed more practice." },
  { en: "diligent", def: "working hard and steadily", lv: 3, pos: "adj", ex: "The diligent student finished every practice problem in the workbook." },
  { en: "feasible", def: "possible to do in real life", lv: 3, pos: "adj", ex: "Building a real rocket in the garage is not feasible." },
  { en: "inevitable", def: "certain to happen, impossible to avoid", lv: 3, pos: "adj", ex: "With a foot of snow falling, a snow day felt inevitable." },
  { en: "lenient", def: "not strict about rules or punishment", lv: 3, pos: "adj", ex: "The substitute was lenient and let us talk during study hall." },
  { en: "mediocre", def: "only okay, not very good", lv: 3, pos: "adj", ex: "The movie was mediocre, but the popcorn was amazing." },
  { en: "meager", def: "too small in amount", lv: 3, pos: "adj", ex: "Our meager lunch of crackers was not enough after the long swim." },
  { en: "plausible", def: "seeming likely to be true", lv: 3, pos: "adj", ex: "His excuse sounded plausible, but the teacher still did not believe it." },
  { en: "prominent", def: "sticking out so it catches the eye", lv: 3, pos: "adj", ex: "The castle stood in a prominent spot on top of the hill." },
  { en: "resilient", def: "able to bounce back quickly from trouble", lv: 3, pos: "adj", ex: "Our team was resilient and came back after losing the first game." },
  { en: "skeptical", def: "doubting that something is true", lv: 3, pos: "adj", ex: "I was skeptical when my friend said he saw a UFO." },
  { en: "volatile", def: "likely to change suddenly and wildly", lv: 3, pos: "adj", ex: "The volcano is volatile and could erupt at any moment." },
  { en: "versatile", def: "able to do many different things well", lv: 3, pos: "adj", ex: "Ana is a versatile athlete who plays soccer, tennis and hockey." },
  { en: "anonymous", def: "with a name that is kept secret", lv: 3, pos: "adj", ex: "An anonymous donor paid for new uniforms for the whole team." },
  { en: "arrogant", def: "acting as if you are better than others", lv: 3, pos: "adj", ex: "The arrogant player bragged before the game and then lost badly." },
  { en: "dormant", def: "inactive for now, as if asleep", lv: 3, pos: "adj", ex: "The volcano has been dormant for five hundred years." },
  { en: "hectic", def: "very busy and full of rushing", lv: 3, pos: "adj", ex: "Saturday was hectic, with two soccer games and a birthday party." },
  { en: "exotic", def: "unusual and from a faraway place", lv: 3, pos: "adj", ex: "The pet store had exotic lizards from the rainforests of Madagascar." },
  { en: "tranquil", def: "calm, quiet and peaceful", lv: 3, pos: "adj", ex: "The lake was tranquil at dawn, with no wind at all." },
  { en: "vulnerable", def: "easy to hurt or attack", lv: 3, pos: "adj", ex: "The turtle is vulnerable when it pokes its head out of its shell." },
  { en: "compel", def: "force someone to do something", lv: 3, pos: "verb", ex: "The league rules compel every player to wear a helmet." },
  { en: "deduce", def: "figure out from the clues you have", lv: 3, pos: "verb", ex: "From the muddy paw prints, we could deduce that the dog had been on the couch." },
  { en: "anticipate", def: "expect something and get ready for it", lv: 3, pos: "verb", ex: "Good goalies anticipate where the shot will go before it is taken." },
  { en: "analyze", def: "study the parts of something closely", lv: 3, pos: "verb", ex: "Scientists analyze rock samples to learn how old they are." },
  { en: "compile", def: "collect information into one list or book", lv: 3, pos: "verb", ex: "We will compile all our weather data into one big chart." },
  { en: "illuminate", def: "light something up", lv: 3, pos: "verb", ex: "Glow sticks illuminate the tent when the flashlight dies." },
  { en: "salvage", def: "save useful things from a wreck", lv: 3, pos: "verb", ex: "Divers tried to salvage gold coins from the sunken ship." },
  { en: "alter", def: "make something different", lv: 3, pos: "verb", ex: "The storm forced us to alter our camping plans." },
  { en: "coincide", def: "happen at the same time as something else", lv: 3, pos: "verb", ex: "My birthday will coincide with the championship game this year." },
  { en: "collaborate", def: "work together with others on something", lv: 3, pos: "verb", ex: "The two classes will collaborate on a giant robot project." },
  { en: "comprehend", def: "understand something fully", lv: 3, pos: "verb", ex: "I could not comprehend how the magician pulled off that trick." },
  { en: "contradict", def: "say the opposite of what someone said", lv: 3, pos: "verb", ex: "Don't contradict the referee, or you might get a yellow card." },
  { en: "dominate", def: "control or be much stronger than others", lv: 3, pos: "verb", ex: "Their team will dominate the league if their star player returns." },
  { en: "emerge", def: "come out into view", lv: 3, pos: "verb", ex: "We waited quietly for the bear cubs to emerge from their den." },
  { en: "evaluate", def: "judge how good or useful something is", lv: 3, pos: "verb", ex: "The judges will evaluate each robot on speed and design." },
  { en: "exclude", def: "keep someone or something out", lv: 3, pos: "verb", ex: "It's unkind to exclude the new kid from the lunch table." },
  { en: "fluctuate", def: "go up and down again and again", lv: 3, pos: "verb", ex: "Temperatures in the desert fluctuate wildly between day and night." },
  { en: "justify", def: "give good reasons for an action", lv: 3, pos: "verb", ex: "Can you justify spending all your birthday money on one game?" },
  { en: "negotiate", def: "talk things over to reach an agreement", lv: 3, pos: "verb", ex: "I tried to negotiate a later bedtime with my parents." },
  { en: "perceive", def: "notice or sense something", lv: 3, pos: "verb", ex: "Dogs can perceive sounds that humans cannot hear at all." },
  { en: "provoke", def: "make someone angry on purpose", lv: 3, pos: "verb", ex: "Don't poke the hornet nest or you will provoke them." },
  { en: "restrain", def: "physically hold someone or something back", lv: 3, pos: "verb", ex: "I had to restrain my dog when he saw the squirrel." },
  { en: "simulate", def: "create a realistic copy of something", lv: 3, pos: "verb", ex: "The flight game can simulate landing a jet on an aircraft carrier." },
  { en: "verify", def: "check that something is true", lv: 3, pos: "verb", ex: "Use two sources to verify any fact you find online." },
  { en: "dilemma", def: "a hard choice between two options", lv: 3, pos: "noun", ex: "I faced a dilemma: go to the party or go to the game." },
  { en: "catastrophe", def: "a terrible disaster", lv: 3, pos: "noun", ex: "Forgetting the tent on a camping trip would be a catastrophe." },
  { en: "mentor", def: "a wise, trusted guide", lv: 3, pos: "noun", ex: "My older cousin became my mentor when I started skateboarding." },
  { en: "verdict", def: "a final decision, especially in court", lv: 3, pos: "noun", ex: "The jury announced its verdict after two days of discussion." },
  { en: "chaos", def: "complete confusion and disorder", lv: 3, pos: "noun", ex: "When the hamster escaped, the classroom turned into total chaos." },
  { en: "compromise", def: "a deal where each side gives up something", lv: 3, pos: "noun", ex: "As a compromise, we watched one show I picked and one my sister picked." },
  { en: "deficit", def: "the amount by which something falls short", lv: 3, pos: "noun", ex: "We came back from a ten-point deficit to win the game." },
  { en: "epidemic", def: "a disease spreading quickly to many people", lv: 3, pos: "noun", ex: "The flu epidemic closed several schools in our district." },
  { en: "hierarchy", def: "a ranking system from highest to lowest", lv: 3, pos: "noun", ex: "In a wolf pack, there is a strict hierarchy with leaders at the top." },
  { en: "hypothesis", def: "a guess you can test with an experiment", lv: 3, pos: "noun", ex: "My hypothesis is that plants will grow faster with music." },
  { en: "incentive", def: "a reward that encourages you to act", lv: 3, pos: "noun", ex: "The incentive for reading twenty books was a free pizza party." },
  { en: "motive", def: "the reason someone does something", lv: 3, pos: "noun", ex: "The detective wanted to find the thief's motive." },
  { en: "perspective", def: "a way of looking at something", lv: 3, pos: "noun", ex: "From the goalie's perspective, the shot looked impossible to stop." },
  { en: "phenomenon", def: "an amazing event in nature or science", lv: 3, pos: "noun", ex: "The northern lights are a phenomenon that people travel far to see." },
  { en: "prototype", def: "the first test model of a new machine", lv: 3, pos: "noun", ex: "Our prototype drone crashed twice before it finally flew." },
  { en: "sanctuary", def: "a safe place where animals are protected", lv: 3, pos: "noun", ex: "The bird sanctuary protects hundreds of birds every winter." },
  { en: "saga", def: "a long story full of adventures", lv: 3, pos: "noun", ex: "The video game saga continues across five different games." },
  { en: "sequel", def: "a book or movie that continues a story", lv: 3, pos: "noun", ex: "I can't wait for the sequel to my favorite superhero movie." },
  { en: "stamina", def: "the energy to keep going for a long time", lv: 3, pos: "noun", ex: "Marathon runners need incredible stamina to finish the race." },
  { en: "trait", def: "a quality that makes someone who they are", lv: 3, pos: "noun", ex: "Patience is a trait that makes my coach so good with beginners." },
  { en: "aftermath", def: "the troubled period following a disaster", lv: 3, pos: "noun", ex: "In the aftermath of the hurricane, neighbors helped each other clean up." },
  { en: "momentum", def: "the force something gains as it moves", lv: 3, pos: "noun", ex: "Our team gained momentum after the first goal and never looked back." },
  { en: "anecdote", def: "a short, funny or interesting true story", lv: 3, pos: "noun", ex: "Grandpa told an anecdote about the time he met a famous astronaut." },
  { en: "protagonist", def: "the main character in a story", lv: 3, pos: "noun", ex: "The protagonist of the book is a boy who discovers a dragon egg." },
  { en: "simultaneously", def: "at exactly the same moment", lv: 3, pos: "adv", ex: "The two runners crossed the finish line simultaneously." },
  { en: "approximately", def: "close to, but not exactly", lv: 3, pos: "adv", ex: "The trip to the stadium takes approximately forty minutes." },
  { en: "scarcely", def: "almost not at all", lv: 3, pos: "adv", ex: "We could scarcely see the trail through the thick fog." },
  { en: "subsequently", def: "afterward, as a result", lv: 3, pos: "adv", ex: "He broke his wrist and subsequently missed the rest of the season." },

  // ---------- Level 4 ----------
  { en: "meticulous", def: "very careful about every small detail", lv: 4, pos: "adj", ex: "Maya was meticulous about her Lego builds, sorting every piece by color." },
  { en: "eloquent", def: "speaking in a clear, powerful, moving way", lv: 4, pos: "adj", ex: "The class president gave an eloquent speech that made everyone cheer." },
  { en: "hypothetical", def: "imagined as a possibility, not real", lv: 4, pos: "adj", ex: "In a hypothetical battle, who would win: a shark or a gorilla?" },
  { en: "lucrative", def: "making a lot of money", lv: 4, pos: "adj", ex: "Selling lemonade during the parade was surprisingly lucrative." },
  { en: "unanimous", def: "with every single person agreeing", lv: 4, pos: "adj", ex: "The vote was unanimous: everyone wanted pizza for the party." },
  { en: "frugal", def: "careful not to waste money", lv: 4, pos: "adj", ex: "My frugal grandma saves and reuses wrapping paper every year." },
  { en: "spontaneous", def: "done suddenly without planning", lv: 4, pos: "adj", ex: "We took a spontaneous trip to the beach on the first warm day." },
  { en: "shrewd", def: "clever at judging situations to get ahead", lv: 4, pos: "adj", ex: "The shrewd trader swapped one card for three better ones." },
  { en: "gullible", def: "easily tricked into believing things", lv: 4, pos: "adj", ex: "My gullible little brother believed me when I said the moon is made of cheese." },
  { en: "arduous", def: "very difficult and tiring", lv: 4, pos: "adj", ex: "The climb up the volcano was arduous, but the view was worth it." },
  { en: "audacious", def: "bold and willing to take big risks", lv: 4, pos: "adj", ex: "The audacious skateboarder tried a trick nobody had ever landed." },
  { en: "complacent", def: "too satisfied to keep working hard", lv: 4, pos: "adj", ex: "After winning ten games, we got complacent and lost to the worst team." },
  { en: "exuberant", def: "full of energy and cheerful excitement", lv: 4, pos: "adj", ex: "The exuberant fans danced in the stands after the winning goal." },
  { en: "formidable", def: "so strong that it causes fear or respect", lv: 4, pos: "adj", ex: "The defending champions were a formidable team to face in the final." },
  { en: "impartial", def: "fair and not taking sides", lv: 4, pos: "adj", ex: "A referee must be impartial, even if his own son is playing." },
  { en: "obscure", def: "not famous or widely known", lv: 4, pos: "adj", ex: "My uncle loves obscure bands that nobody else has heard of." },
  { en: "inept", def: "having no skill at all", lv: 4, pos: "adj", ex: "I was so inept at chess that I lost in four moves." },
  { en: "innate", def: "present since birth, not learned", lv: 4, pos: "adj", ex: "Some kids have an innate talent for music and can play by ear." },
  { en: "mundane", def: "ordinary and dull, part of everyday life", lv: 4, pos: "adj", ex: "Even superheroes have to do mundane things like laundry." },
  { en: "nonchalant", def: "calm and casual, seeming not to care", lv: 4, pos: "adj", ex: "He looked nonchalant at the plate, as if the bases were not loaded." },
  { en: "ominous", def: "seeming to warn of something bad", lv: 4, pos: "adj", ex: "We heard an ominous rumble from deep inside the cave." },
  { en: "opulent", def: "rich, fancy and luxurious", lv: 4, pos: "adj", ex: "The hotel lobby was opulent, with gold railings and crystal lights." },
  { en: "tangible", def: "real enough to be touched", lv: 4, pos: "adj", ex: "The trophy was tangible proof of all our hard work." },
  { en: "succinct", def: "said clearly using few words", lv: 4, pos: "adj", ex: "Keep your book report succinct, because one page is enough." },
  { en: "trivial", def: "small and not important", lv: 4, pos: "adj", ex: "Don't argue over trivial things like who sits where." },
  { en: "vindictive", def: "wanting to get revenge", lv: 4, pos: "adj", ex: "The vindictive villain swore to get back at the hero." },
  { en: "voracious", def: "wanting huge amounts, extremely hungry", lv: 4, pos: "adj", ex: "My voracious little brother eats three bowls of cereal every morning." },
  { en: "pensive", def: "quietly thinking deeply", lv: 4, pos: "adj", ex: "Grandpa sat on the porch looking pensive after the game." },
  { en: "refute", def: "prove a claim is wrong", lv: 4, pos: "verb", ex: "The scientist used data to refute the idea that the Earth is flat." },
  { en: "scrutinize", def: "inspect with a critical eye to find any problems", lv: 4, pos: "verb", ex: "The referees scrutinize the replay to see if the ball crossed the line." },
  { en: "alleviate", def: "make pain or trouble less severe", lv: 4, pos: "verb", ex: "Ice can alleviate the swelling from a twisted ankle." },
  { en: "concede", def: "admit that you have lost or were wrong", lv: 4, pos: "verb", ex: "Down two rooks, I had to concede the chess match." },
  { en: "deplete", def: "use up most of a supply", lv: 4, pos: "verb", ex: "Running all day will deplete your energy, so eat a good breakfast." },
  { en: "deter", def: "discourage someone from doing something", lv: 4, pos: "verb", ex: "The tall fence is supposed to deter deer from eating our garden." },
  { en: "discern", def: "notice small differences between things", lv: 4, pos: "verb", ex: "Can you discern the real diamond from the fake one?" },
  { en: "elicit", def: "draw out a reaction or answer", lv: 4, pos: "verb", ex: "The comedian's joke failed to elicit even one laugh." },
  { en: "exacerbate", def: "make a bad situation worse", lv: 4, pos: "verb", ex: "Scratching a mosquito bite will only exacerbate the itch." },
  { en: "fabricate", def: "invent a fake story or excuse", lv: 4, pos: "verb", ex: "Don't fabricate an excuse; just tell the teacher what happened." },
  { en: "implore", def: "beg someone desperately", lv: 4, pos: "verb", ex: "I implore you, please don't tell Mom about the broken lamp." },
  { en: "ponder", def: "think about something carefully for a while", lv: 4, pos: "verb", ex: "Take a minute to ponder your next chess move." },
  { en: "procrastinate", def: "put off a task until later", lv: 4, pos: "verb", ex: "If you procrastinate on your project, you will be up all night." },
  { en: "rectify", def: "fix something that is wrong", lv: 4, pos: "verb", ex: "The coach promised to rectify the mistake in the team roster." },
  { en: "reiterate", def: "say something again for emphasis", lv: 4, pos: "verb", ex: "Let me reiterate: nobody touches the experiment without goggles." },
  { en: "stifle", def: "hold back a laugh, yawn or sound", lv: 4, pos: "verb", ex: "I tried to stifle a laugh when the teacher's chair squeaked." },
  { en: "thwart", def: "stop someone's plan from working", lv: 4, pos: "verb", ex: "The hero raced to thwart the villain's plan to steal the diamond." },
  { en: "undermine", def: "slowly weaken something from below or in secret", lv: 4, pos: "verb", ex: "Arguing with each other will undermine our team spirit." },
  { en: "advocate", def: "speak up in support of a cause", lv: 4, pos: "verb", ex: "Students will advocate for a longer recess at the school board meeting." },
  { en: "coax", def: "get someone to act with gentle, patient urging", lv: 4, pos: "verb", ex: "I tried to coax the scared puppy out from under the porch." },
  { en: "enhance", def: "make something better or stronger", lv: 4, pos: "verb", ex: "A new graphics card will enhance the game's visuals." },
  { en: "hoard", def: "secretly collect and store a large supply", lv: 4, pos: "verb", ex: "Squirrels hoard acorns so they can survive the winter." },
  { en: "loathe", def: "hate very strongly", lv: 4, pos: "verb", ex: "I loathe the smell of boiled cabbage in the cafeteria." },
  { en: "squander", def: "waste money or chances foolishly", lv: 4, pos: "verb", ex: "Don't squander your power-ups early in the level." },
  { en: "anomaly", def: "something unusual that breaks the pattern", lv: 4, pos: "noun", ex: "The scientists noticed an anomaly in the signal from the space probe." },
  { en: "consensus", def: "an opinion most of a group shares", lv: 4, pos: "noun", ex: "The consensus in our class was that the field trip should be to the space museum." },
  { en: "nemesis", def: "a longtime enemy who is hard to beat", lv: 4, pos: "noun", ex: "In the comics, Batman's nemesis is always plotting a new escape." },
  { en: "adversity", def: "hard times and difficult problems", lv: 4, pos: "noun", ex: "The team showed courage in the face of adversity after losing their star player." },
  { en: "animosity", def: "strong unfriendly feelings toward someone", lv: 4, pos: "noun", ex: "There was animosity between the two rival schools for decades." },
  { en: "aptitude", def: "a natural ability to learn something", lv: 4, pos: "noun", ex: "Mia has an aptitude for math and solves puzzles in seconds." },
  { en: "benefactor", def: "a person who gives money to help", lv: 4, pos: "noun", ex: "A mysterious benefactor paid for the new playground." },
  { en: "bravado", def: "showy boldness meant to impress others", lv: 4, pos: "noun", ex: "His bravado disappeared when he saw the giant roller coaster." },
  { en: "camaraderie", def: "friendship and trust within a group", lv: 4, pos: "noun", ex: "The camaraderie on our team makes even hard practices fun." },
  { en: "catalyst", def: "something that causes a change to happen", lv: 4, pos: "noun", ex: "The new coach was the catalyst for our winning streak." },
  { en: "demeanor", def: "the way someone looks and behaves", lv: 4, pos: "noun", ex: "The pilot's calm demeanor made the passengers feel safe." },
  { en: "dexterity", def: "skill and quickness with your hands", lv: 4, pos: "noun", ex: "Juggling five balls at once takes amazing dexterity." },
  { en: "discrepancy", def: "a difference between things that should match", lv: 4, pos: "noun", ex: "There was a discrepancy between the score on the board and the referee's card." },
  { en: "enigma", def: "a person or thing that is a total mystery", lv: 4, pos: "noun", ex: "How the cat got onto the roof remains an enigma." },
  { en: "fiasco", def: "a complete and embarrassing failure", lv: 4, pos: "noun", ex: "The science fair volcano was a fiasco when it exploded early." },
  { en: "integrity", def: "the quality of being honest and fair", lv: 4, pos: "noun", ex: "He showed integrity by admitting the ball was out." },
  { en: "jargon", def: "special words used by one group", lv: 4, pos: "noun", ex: "Gamers use jargon like nerf and buff that parents do not understand." },
  { en: "novice", def: "a beginner with little experience", lv: 4, pos: "noun", ex: "As a novice snowboarder, I spent most of the day sitting in the snow." },
  { en: "nostalgia", def: "a warm longing for the past", lv: 4, pos: "noun", ex: "Dad felt nostalgia when he found his old video game console in the attic." },
  { en: "precedent", def: "an earlier event used as an example", lv: 4, pos: "noun", ex: "Letting one student skip homework would set a bad precedent." },
  { en: "prodigy", def: "a young person with amazing talent", lv: 4, pos: "noun", ex: "The chess prodigy beat a grandmaster when she was only ten." },
  { en: "remorse", def: "deep regret for doing something wrong", lv: 4, pos: "noun", ex: "He felt remorse after breaking his brother's model plane." },
  { en: "tenacity", def: "refusal to quit, no matter what", lv: 4, pos: "noun", ex: "Her tenacity helped her finish the marathon after falling twice." },
  { en: "zenith", def: "the highest point of success or power", lv: 4, pos: "noun", ex: "Winning the championship was the zenith of his career." },
  { en: "inadvertently", def: "by accident, without meaning to", lv: 4, pos: "adv", ex: "I inadvertently deleted my saved game while cleaning up files." },
  { en: "vehemently", def: "with strong, forceful feeling", lv: 4, pos: "adv", ex: "My sister vehemently denied eating the last cookie." },
  { en: "haphazardly", def: "in a messy, random way", lv: 4, pos: "adv", ex: "The toys were thrown haphazardly into the closet before the guests arrived." },
  { en: "incessantly", def: "without stopping, again and again", lv: 4, pos: "adv", ex: "The dog barked incessantly at the mail truck." },

  // ---------- Level 5 (grades 7-8 stretch) ----------
  { en: "ubiquitous", def: "seeming to be everywhere at once", lv: 5, pos: "adj", ex: "Smartphones are ubiquitous now; even my grandma has two." },
  { en: "pragmatic", def: "practical, focused on what actually works", lv: 5, pos: "adj", ex: "Instead of complaining about the flat tire, Dad took a pragmatic approach and fixed it." },
  { en: "ephemeral", def: "lasting only a very short time", lv: 5, pos: "adj", ex: "The rainbow was ephemeral, gone before I could grab my camera." },
  { en: "magnanimous", def: "generous and forgiving, even toward a rival", lv: 5, pos: "adj", ex: "The magnanimous champion helped his opponent up after the match." },
  { en: "gregarious", def: "loving to be around other people", lv: 5, pos: "adj", ex: "My gregarious dog wants to say hello to everyone at the park." },
  { en: "lucid", def: "clear and easy to understand", lv: 5, pos: "adj", ex: "The scientist gave a lucid explanation of how black holes work." },
  { en: "superfluous", def: "more than is needed; extra", lv: 5, pos: "adj", ex: "The extra instructions were superfluous because the game was so easy." },
  { en: "empirical", def: "based on observation and experiment", lv: 5, pos: "adj", ex: "We need empirical evidence, so let's actually test the paper airplanes." },
  { en: "esoteric", def: "so specialized that only experts understand it", lv: 5, pos: "adj", ex: "The professor's lecture was so esoteric that only three people understood it." },
  { en: "garrulous", def: "talking too much about unimportant things", lv: 5, pos: "adj", ex: "The garrulous bus driver told us about his cat for the whole trip." },
  { en: "nefarious", def: "wicked and evil, like a villain", lv: 5, pos: "adj", ex: "The villain had a nefarious plan to steal all the gold in the world." },
  { en: "pernicious", def: "harmful in a slow, hidden way", lv: 5, pos: "adj", ex: "Staying up late every night can have a pernicious effect on your grades." },
  { en: "quixotic", def: "noble but wildly unrealistic", lv: 5, pos: "adj", ex: "His quixotic plan to dig a tunnel to China ended after one afternoon." },
  { en: "sanguine", def: "cheerful and hopeful about the future", lv: 5, pos: "adj", ex: "The coach stayed sanguine about our chances, even after two losses." },
  { en: "surreptitious", def: "done secretly so nobody notices", lv: 5, pos: "adj", ex: "He took a surreptitious bite of cake before dinner." },
  { en: "taciturn", def: "saying very little; quiet by nature", lv: 5, pos: "adj", ex: "The taciturn goalie rarely spoke, but his saves said everything." },
  { en: "tenuous", def: "barely holding, with little support", lv: 5, pos: "adj", ex: "Our lead was tenuous: just one point with a minute left." },
  { en: "vicarious", def: "felt through someone else's experience", lv: 5, pos: "adj", ex: "I got a vicarious thrill watching my brother ride the giant coaster." },
  { en: "ambivalent", def: "having mixed feelings about something", lv: 5, pos: "adj", ex: "I felt ambivalent about moving: excited for a new house but sad to leave friends." },
  { en: "cantankerous", def: "grumpy and quick to argue", lv: 5, pos: "adj", ex: "The cantankerous old man yelled at us to get off his lawn." },
  { en: "indomitable", def: "never giving in, whatever happens", lv: 5, pos: "adj", ex: "The underdog team showed an indomitable spirit all season." },
  { en: "precocious", def: "showing skills early, beyond your age", lv: 5, pos: "adj", ex: "The precocious six-year-old was already reading chapter books." },
  { en: "prolific", def: "producing a great amount of work", lv: 5, pos: "adj", ex: "The prolific author has written over fifty adventure novels." },
  { en: "sporadic", def: "happening now and then, at random", lv: 5, pos: "adj", ex: "There was sporadic rain throughout the baseball game." },
  { en: "stoic", def: "calmly accepting pain without complaining", lv: 5, pos: "adj", ex: "He stayed stoic while the nurse cleaned the scrape on his knee." },
  { en: "innocuous", def: "harmless and not likely to offend", lv: 5, pos: "adj", ex: "The snake looked scary, but it was completely innocuous." },
  { en: "lackadaisical", def: "lazy and without effort or care", lv: 5, pos: "adj", ex: "His lackadaisical attitude at practice annoyed the coach." },
  { en: "whimsical", def: "playful and fanciful in an odd way", lv: 5, pos: "adj", ex: "The park had whimsical sculptures of dancing frogs." },
  { en: "obfuscate", def: "make something confusing on purpose", lv: 5, pos: "verb", ex: "The tricky directions seemed designed to obfuscate the real answer." },
  { en: "capitulate", def: "finally give in to demands after resisting", lv: 5, pos: "verb", ex: "After an hour of begging, Mom will usually capitulate and let us get ice cream." },
  { en: "circumvent", def: "find a way around a rule or barrier", lv: 5, pos: "verb", ex: "The hackers in the movie tried to circumvent the security system." },
  { en: "commiserate", def: "share someone's sadness or frustration", lv: 5, pos: "verb", ex: "After the loss, the players went out for pizza to commiserate." },
  { en: "conflate", def: "wrongly mix two ideas into one", lv: 5, pos: "verb", ex: "People often conflate weather and climate, but they are different." },
  { en: "corroborate", def: "support a claim with more evidence", lv: 5, pos: "verb", ex: "Two witnesses can corroborate the story about the escaped llama." },
  { en: "delineate", def: "describe or mark out exactly", lv: 5, pos: "verb", ex: "Orange cones delineate the boundaries of the soccer field." },
  { en: "disseminate", def: "spread information to many people", lv: 5, pos: "verb", ex: "The school uses an app to disseminate news to every family." },
  { en: "eradicate", def: "destroy completely, wiping out", lv: 5, pos: "verb", ex: "Doctors hope to eradicate the disease completely within ten years." },
  { en: "exonerate", def: "clear someone of blame", lv: 5, pos: "verb", ex: "The video footage helped exonerate the boy accused of breaking the window." },
  { en: "extrapolate", def: "use known facts to estimate beyond them", lv: 5, pos: "verb", ex: "From the first three days, we can extrapolate how tall the plant will be in a month." },
  { en: "galvanize", def: "shock or excite people into action", lv: 5, pos: "verb", ex: "The coach's halftime speech managed to galvanize the tired team." },
  { en: "juxtapose", def: "place things side by side to compare", lv: 5, pos: "verb", ex: "The artist likes to juxtapose old castles with modern skyscrapers." },
  { en: "proliferate", def: "increase rapidly in number", lv: 5, pos: "verb", ex: "Rabbits proliferate quickly when there are no foxes around." },
  { en: "reconcile", def: "become friends again after a fight", lv: 5, pos: "verb", ex: "The two best friends tried to reconcile after their argument." },
  { en: "supplant", def: "take the place of something else", lv: 5, pos: "verb", ex: "Electric cars may supplant gas cars within our lifetime." },
  { en: "transcend", def: "go beyond ordinary limits", lv: 5, pos: "verb", ex: "Great music can transcend language and connect people everywhere." },
  { en: "vacillate", def: "keep switching between two choices", lv: 5, pos: "verb", ex: "I always vacillate between pizza and tacos when ordering." },
  { en: "acquiesce", def: "accept something quietly without arguing", lv: 5, pos: "verb", ex: "My brother refused to acquiesce to sharing the controller." },
  { en: "exasperate", def: "annoy someone greatly", lv: 5, pos: "verb", ex: "My little brother's constant questions exasperate me during movies." },
  { en: "extricate", def: "free something from a trap or tangle", lv: 5, pos: "verb", ex: "It took twenty minutes to extricate the kite from the tree." },
  { en: "inundate", def: "flood with too much of something", lv: 5, pos: "verb", ex: "Fans inundate the team with letters after every big win." },
  { en: "placate", def: "calm down someone who is upset", lv: 5, pos: "verb", ex: "I gave my sister my dessert to placate her." },
  { en: "rejuvenate", def: "make feel young and fresh again", lv: 5, pos: "verb", ex: "A swim in the cool lake will rejuvenate everyone after the hike." },
  { en: "cacophony", def: "a harsh mix of loud sounds", lv: 5, pos: "noun", ex: "The band warming up created a cacophony of drums and trumpets." },
  { en: "paradox", def: "a statement that seems impossible yet may be true", lv: 5, pos: "noun", ex: "Time travel creates a paradox: if you stop yourself from leaving, how did you leave?" },
  { en: "panacea", def: "a cure for every problem", lv: 5, pos: "noun", ex: "A new coach is not a panacea for a team that never practices." },
  { en: "epiphany", def: "a sudden flash of understanding", lv: 5, pos: "noun", ex: "I had an epiphany in the shower about how to beat the final boss." },
  { en: "euphemism", def: "a gentle phrase for something unpleasant", lv: 5, pos: "noun", ex: "Saying the old car went to a farm upstate is a euphemism for the junkyard." },
  { en: "hubris", def: "excessive pride that leads to a fall", lv: 5, pos: "noun", ex: "The hare's hubris made him nap during the race, and the tortoise won." },
  { en: "juggernaut", def: "a huge, unstoppable force", lv: 5, pos: "noun", ex: "The undefeated team was a juggernaut that crushed every opponent." },
  { en: "labyrinth", def: "a complicated maze of paths", lv: 5, pos: "noun", ex: "The castle basement was a labyrinth of dark tunnels." },
  { en: "misnomer", def: "a name that does not fit", lv: 5, pos: "noun", ex: "The name guinea pig is a misnomer, since they are not pigs at all." },
  { en: "nuance", def: "a very small, subtle difference", lv: 5, pos: "noun", ex: "Good actors notice every nuance in a script." },
  { en: "onslaught", def: "a fierce, powerful attack", lv: 5, pos: "noun", ex: "The goalie faced an onslaught of shots in the final minutes." },
  { en: "paragon", def: "a perfect example of a quality", lv: 5, pos: "noun", ex: "Our team captain is a paragon of good sportsmanship." },
  { en: "quagmire", def: "a messy situation that is hard to escape", lv: 5, pos: "noun", ex: "The group project became a quagmire when nobody agreed on anything." },
  { en: "serendipity", def: "finding something good by happy accident", lv: 5, pos: "noun", ex: "By pure serendipity, I found twenty dollars in my old jacket." },
  { en: "solace", def: "comfort during sadness", lv: 5, pos: "noun", ex: "After the loss, he found solace in playing fetch with his dog." },
  { en: "travesty", def: "a shockingly bad or unfair version", lv: 5, pos: "noun", ex: "Fans called the referee's terrible call a travesty." },
  { en: "vestige", def: "a small trace of something that is gone", lv: 5, pos: "noun", ex: "A few stones are the last vestige of the old castle." },
  { en: "zealot", def: "a person with extreme beliefs or devotion", lv: 5, pos: "noun", ex: "My uncle is a football zealot who paints his face for every game." },
  { en: "dichotomy", def: "a division into two opposite parts", lv: 5, pos: "noun", ex: "The book shows a dichotomy between good and evil." },
  { en: "facade", def: "a false appearance hiding the truth", lv: 5, pos: "noun", ex: "His tough facade crumbled when he saw the puppy." },
  { en: "impasse", def: "a point where no progress is possible", lv: 5, pos: "noun", ex: "The trade talks hit an impasse when neither side would give up a player." },
  { en: "nadir", def: "the lowest point of something", lv: 5, pos: "noun", ex: "Losing ten games in a row was the nadir of our season." },
  { en: "charlatan", def: "a fake who pretends to have skills", lv: 5, pos: "noun", ex: "The charlatan sold bottles of colored water as magic potions." },
  { en: "harbinger", def: "a sign of something coming", lv: 5, pos: "noun", ex: "The first robin is a harbinger of spring." },
  { en: "ostensibly", def: "seemingly true, but maybe not really", lv: 5, pos: "adv", ex: "He went to the library, ostensibly to study, but he played games." },
  { en: "inexplicably", def: "in a way that cannot be explained", lv: 5, pos: "adv", ex: "The lights inexplicably turned on in the empty gym." },
  { en: "unequivocally", def: "clearly and without any doubt", lv: 5, pos: "adv", ex: "That was unequivocally the best game I have ever played." },
  { en: "precariously", def: "in an unsteady way, likely to fall", lv: 5, pos: "adv", ex: "The stack of books balanced precariously on the edge of the desk." },
];
